apiVersion: v1
kind: Secret
metadata:
  name: optimization-secrets
  namespace: foodsea
type: Opaque
stringData:
  DB_URL: postgres://postgres:changeme@optimization-postgres:5432/optimization_db?sslmode=require
  DB_USER: postgres
  DB_PASSWORD: changeme
