// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Brand is the predicate function for brand builders.
type Brand func(*sql.Selector)

// Cart is the predicate function for cart builders.
type Cart func(*sql.Selector)

// CartItem is the predicate function for cartitem builders.
type CartItem func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// DeliveryCondition is the predicate function for deliverycondition builders.
type DeliveryCondition func(*sql.Selector)

// Offer is the predicate function for offer builders.
type Offer func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// ProductNutrition is the predicate function for productnutrition builders.
type ProductNutrition func(*sql.Selector)

// Store is the predicate function for store builders.
type Store func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
