// Code generated by ent, DO NOT EDIT.

package orderliveactivity

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/foodsea/core/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEQ(FieldUserID, v))
}

// PushToken applies equality check predicate on the "push_token" field. It's identical to PushTokenEQ.
func PushToken(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEQ(FieldPushToken, v))
}

// BundleID applies equality check predicate on the "bundle_id" field. It's identical to BundleIDEQ.
func BundleID(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEQ(FieldBundleID, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEQ(FieldStartedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldNotIn(FieldUserID, vs...))
}

// PushTokenEQ applies the EQ predicate on the "push_token" field.
func PushTokenEQ(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEQ(FieldPushToken, v))
}

// PushTokenNEQ applies the NEQ predicate on the "push_token" field.
func PushTokenNEQ(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldNEQ(FieldPushToken, v))
}

// PushTokenIn applies the In predicate on the "push_token" field.
func PushTokenIn(vs ...string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldIn(FieldPushToken, vs...))
}

// PushTokenNotIn applies the NotIn predicate on the "push_token" field.
func PushTokenNotIn(vs ...string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldNotIn(FieldPushToken, vs...))
}

// PushTokenGT applies the GT predicate on the "push_token" field.
func PushTokenGT(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldGT(FieldPushToken, v))
}

// PushTokenGTE applies the GTE predicate on the "push_token" field.
func PushTokenGTE(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldGTE(FieldPushToken, v))
}

// PushTokenLT applies the LT predicate on the "push_token" field.
func PushTokenLT(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldLT(FieldPushToken, v))
}

// PushTokenLTE applies the LTE predicate on the "push_token" field.
func PushTokenLTE(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldLTE(FieldPushToken, v))
}

// PushTokenContains applies the Contains predicate on the "push_token" field.
func PushTokenContains(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldContains(FieldPushToken, v))
}

// PushTokenHasPrefix applies the HasPrefix predicate on the "push_token" field.
func PushTokenHasPrefix(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldHasPrefix(FieldPushToken, v))
}

// PushTokenHasSuffix applies the HasSuffix predicate on the "push_token" field.
func PushTokenHasSuffix(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldHasSuffix(FieldPushToken, v))
}

// PushTokenEqualFold applies the EqualFold predicate on the "push_token" field.
func PushTokenEqualFold(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEqualFold(FieldPushToken, v))
}

// PushTokenContainsFold applies the ContainsFold predicate on the "push_token" field.
func PushTokenContainsFold(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldContainsFold(FieldPushToken, v))
}

// BundleIDEQ applies the EQ predicate on the "bundle_id" field.
func BundleIDEQ(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEQ(FieldBundleID, v))
}

// BundleIDNEQ applies the NEQ predicate on the "bundle_id" field.
func BundleIDNEQ(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldNEQ(FieldBundleID, v))
}

// BundleIDIn applies the In predicate on the "bundle_id" field.
func BundleIDIn(vs ...string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldIn(FieldBundleID, vs...))
}

// BundleIDNotIn applies the NotIn predicate on the "bundle_id" field.
func BundleIDNotIn(vs ...string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldNotIn(FieldBundleID, vs...))
}

// BundleIDGT applies the GT predicate on the "bundle_id" field.
func BundleIDGT(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldGT(FieldBundleID, v))
}

// BundleIDGTE applies the GTE predicate on the "bundle_id" field.
func BundleIDGTE(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldGTE(FieldBundleID, v))
}

// BundleIDLT applies the LT predicate on the "bundle_id" field.
func BundleIDLT(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldLT(FieldBundleID, v))
}

// BundleIDLTE applies the LTE predicate on the "bundle_id" field.
func BundleIDLTE(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldLTE(FieldBundleID, v))
}

// BundleIDContains applies the Contains predicate on the "bundle_id" field.
func BundleIDContains(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldContains(FieldBundleID, v))
}

// BundleIDHasPrefix applies the HasPrefix predicate on the "bundle_id" field.
func BundleIDHasPrefix(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldHasPrefix(FieldBundleID, v))
}

// BundleIDHasSuffix applies the HasSuffix predicate on the "bundle_id" field.
func BundleIDHasSuffix(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldHasSuffix(FieldBundleID, v))
}

// BundleIDEqualFold applies the EqualFold predicate on the "bundle_id" field.
func BundleIDEqualFold(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEqualFold(FieldBundleID, v))
}

// BundleIDContainsFold applies the ContainsFold predicate on the "bundle_id" field.
func BundleIDContainsFold(v string) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldContainsFold(FieldBundleID, v))
}

// EnvironmentEQ applies the EQ predicate on the "environment" field.
func EnvironmentEQ(v Environment) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEQ(FieldEnvironment, v))
}

// EnvironmentNEQ applies the NEQ predicate on the "environment" field.
func EnvironmentNEQ(v Environment) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldNEQ(FieldEnvironment, v))
}

// EnvironmentIn applies the In predicate on the "environment" field.
func EnvironmentIn(vs ...Environment) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldIn(FieldEnvironment, vs...))
}

// EnvironmentNotIn applies the NotIn predicate on the "environment" field.
func EnvironmentNotIn(vs ...Environment) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldNotIn(FieldEnvironment, vs...))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldLTE(FieldStartedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrderLiveActivity) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrderLiveActivity) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrderLiveActivity) predicate.OrderLiveActivity {
	return predicate.OrderLiveActivity(sql.NotPredicates(p))
}
