// Code generated by ent, DO NOT EDIT.

package optimizationresult

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/foodsea/optimization/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldUpdatedAt, v))
}

// TotalKopecks applies equality check predicate on the "total_kopecks" field. It's identical to TotalKopecksEQ.
func TotalKopecks(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldTotalKopecks, v))
}

// DeliveryKopecks applies equality check predicate on the "delivery_kopecks" field. It's identical to DeliveryKopecksEQ.
func DeliveryKopecks(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldDeliveryKopecks, v))
}

// SavingsKopecks applies equality check predicate on the "savings_kopecks" field. It's identical to SavingsKopecksEQ.
func SavingsKopecks(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldSavingsKopecks, v))
}

// CartHash applies equality check predicate on the "cart_hash" field. It's identical to CartHashEQ.
func CartHash(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldCartHash, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldStatus, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldUserID, v))
}

// IsApproximate applies equality check predicate on the "is_approximate" field. It's identical to IsApproximateEQ.
func IsApproximate(v bool) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldIsApproximate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLTE(FieldUpdatedAt, v))
}

// TotalKopecksEQ applies the EQ predicate on the "total_kopecks" field.
func TotalKopecksEQ(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldTotalKopecks, v))
}

// TotalKopecksNEQ applies the NEQ predicate on the "total_kopecks" field.
func TotalKopecksNEQ(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNEQ(FieldTotalKopecks, v))
}

// TotalKopecksIn applies the In predicate on the "total_kopecks" field.
func TotalKopecksIn(vs ...int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldIn(FieldTotalKopecks, vs...))
}

// TotalKopecksNotIn applies the NotIn predicate on the "total_kopecks" field.
func TotalKopecksNotIn(vs ...int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNotIn(FieldTotalKopecks, vs...))
}

// TotalKopecksGT applies the GT predicate on the "total_kopecks" field.
func TotalKopecksGT(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGT(FieldTotalKopecks, v))
}

// TotalKopecksGTE applies the GTE predicate on the "total_kopecks" field.
func TotalKopecksGTE(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGTE(FieldTotalKopecks, v))
}

// TotalKopecksLT applies the LT predicate on the "total_kopecks" field.
func TotalKopecksLT(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLT(FieldTotalKopecks, v))
}

// TotalKopecksLTE applies the LTE predicate on the "total_kopecks" field.
func TotalKopecksLTE(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLTE(FieldTotalKopecks, v))
}

// DeliveryKopecksEQ applies the EQ predicate on the "delivery_kopecks" field.
func DeliveryKopecksEQ(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldDeliveryKopecks, v))
}

// DeliveryKopecksNEQ applies the NEQ predicate on the "delivery_kopecks" field.
func DeliveryKopecksNEQ(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNEQ(FieldDeliveryKopecks, v))
}

// DeliveryKopecksIn applies the In predicate on the "delivery_kopecks" field.
func DeliveryKopecksIn(vs ...int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldIn(FieldDeliveryKopecks, vs...))
}

// DeliveryKopecksNotIn applies the NotIn predicate on the "delivery_kopecks" field.
func DeliveryKopecksNotIn(vs ...int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNotIn(FieldDeliveryKopecks, vs...))
}

// DeliveryKopecksGT applies the GT predicate on the "delivery_kopecks" field.
func DeliveryKopecksGT(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGT(FieldDeliveryKopecks, v))
}

// DeliveryKopecksGTE applies the GTE predicate on the "delivery_kopecks" field.
func DeliveryKopecksGTE(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGTE(FieldDeliveryKopecks, v))
}

// DeliveryKopecksLT applies the LT predicate on the "delivery_kopecks" field.
func DeliveryKopecksLT(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLT(FieldDeliveryKopecks, v))
}

// DeliveryKopecksLTE applies the LTE predicate on the "delivery_kopecks" field.
func DeliveryKopecksLTE(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLTE(FieldDeliveryKopecks, v))
}

// SavingsKopecksEQ applies the EQ predicate on the "savings_kopecks" field.
func SavingsKopecksEQ(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldSavingsKopecks, v))
}

// SavingsKopecksNEQ applies the NEQ predicate on the "savings_kopecks" field.
func SavingsKopecksNEQ(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNEQ(FieldSavingsKopecks, v))
}

// SavingsKopecksIn applies the In predicate on the "savings_kopecks" field.
func SavingsKopecksIn(vs ...int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldIn(FieldSavingsKopecks, vs...))
}

// SavingsKopecksNotIn applies the NotIn predicate on the "savings_kopecks" field.
func SavingsKopecksNotIn(vs ...int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNotIn(FieldSavingsKopecks, vs...))
}

// SavingsKopecksGT applies the GT predicate on the "savings_kopecks" field.
func SavingsKopecksGT(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGT(FieldSavingsKopecks, v))
}

// SavingsKopecksGTE applies the GTE predicate on the "savings_kopecks" field.
func SavingsKopecksGTE(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGTE(FieldSavingsKopecks, v))
}

// SavingsKopecksLT applies the LT predicate on the "savings_kopecks" field.
func SavingsKopecksLT(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLT(FieldSavingsKopecks, v))
}

// SavingsKopecksLTE applies the LTE predicate on the "savings_kopecks" field.
func SavingsKopecksLTE(v int64) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLTE(FieldSavingsKopecks, v))
}

// CartHashEQ applies the EQ predicate on the "cart_hash" field.
func CartHashEQ(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldCartHash, v))
}

// CartHashNEQ applies the NEQ predicate on the "cart_hash" field.
func CartHashNEQ(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNEQ(FieldCartHash, v))
}

// CartHashIn applies the In predicate on the "cart_hash" field.
func CartHashIn(vs ...string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldIn(FieldCartHash, vs...))
}

// CartHashNotIn applies the NotIn predicate on the "cart_hash" field.
func CartHashNotIn(vs ...string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNotIn(FieldCartHash, vs...))
}

// CartHashGT applies the GT predicate on the "cart_hash" field.
func CartHashGT(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGT(FieldCartHash, v))
}

// CartHashGTE applies the GTE predicate on the "cart_hash" field.
func CartHashGTE(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGTE(FieldCartHash, v))
}

// CartHashLT applies the LT predicate on the "cart_hash" field.
func CartHashLT(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLT(FieldCartHash, v))
}

// CartHashLTE applies the LTE predicate on the "cart_hash" field.
func CartHashLTE(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLTE(FieldCartHash, v))
}

// CartHashContains applies the Contains predicate on the "cart_hash" field.
func CartHashContains(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldContains(FieldCartHash, v))
}

// CartHashHasPrefix applies the HasPrefix predicate on the "cart_hash" field.
func CartHashHasPrefix(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldHasPrefix(FieldCartHash, v))
}

// CartHashHasSuffix applies the HasSuffix predicate on the "cart_hash" field.
func CartHashHasSuffix(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldHasSuffix(FieldCartHash, v))
}

// CartHashEqualFold applies the EqualFold predicate on the "cart_hash" field.
func CartHashEqualFold(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEqualFold(FieldCartHash, v))
}

// CartHashContainsFold applies the ContainsFold predicate on the "cart_hash" field.
func CartHashContainsFold(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldContainsFold(FieldCartHash, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldContainsFold(FieldStatus, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldLTE(FieldUserID, v))
}

// IsApproximateEQ applies the EQ predicate on the "is_approximate" field.
func IsApproximateEQ(v bool) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldEQ(FieldIsApproximate, v))
}

// IsApproximateNEQ applies the NEQ predicate on the "is_approximate" field.
func IsApproximateNEQ(v bool) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.FieldNEQ(FieldIsApproximate, v))
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.OptimizationResult {
	return predicate.OptimizationResult(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.OptimizationItem) predicate.OptimizationResult {
	return predicate.OptimizationResult(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSubstitutions applies the HasEdge predicate on the "substitutions" edge.
func HasSubstitutions() predicate.OptimizationResult {
	return predicate.OptimizationResult(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SubstitutionsTable, SubstitutionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSubstitutionsWith applies the HasEdge predicate on the "substitutions" edge with a given conditions (other predicates).
func HasSubstitutionsWith(preds ...predicate.Substitution) predicate.OptimizationResult {
	return predicate.OptimizationResult(func(s *sql.Selector) {
		step := newSubstitutionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OptimizationResult) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OptimizationResult) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OptimizationResult) predicate.OptimizationResult {
	return predicate.OptimizationResult(sql.NotPredicates(p))
}
