# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import analogs_pb2 as analogs__pb2

_grpc_experimental = getattr(grpc, "experimental", None)
_GetAnalogsRequest = getattr(analogs__pb2, "GetAnalogsRequest")
_GetAnalogsResponse = getattr(analogs__pb2, "GetAnalogsResponse")
_GetBatchAnalogsRequest = getattr(analogs__pb2, "GetBatchAnalogsRequest")
_GetBatchAnalogsResponse = getattr(analogs__pb2, "GetBatchAnalogsResponse")


class AnalogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnalogs = channel.unary_unary(
                '/ml.AnalogService/GetAnalogs',
                request_serializer=_GetAnalogsRequest.SerializeToString,
                response_deserializer=_GetAnalogsResponse.FromString,
                )
        self.GetBatchAnalogs = channel.unary_unary(
                '/ml.AnalogService/GetBatchAnalogs',
                request_serializer=_GetBatchAnalogsRequest.SerializeToString,
                response_deserializer=_GetBatchAnalogsResponse.FromString,
                )


class AnalogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAnalogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatchAnalogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnalogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalogs,
                    request_deserializer=_GetAnalogsRequest.FromString,
                    response_serializer=_GetAnalogsResponse.SerializeToString,
            ),
            'GetBatchAnalogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatchAnalogs,
                    request_deserializer=_GetBatchAnalogsRequest.FromString,
                    response_serializer=_GetBatchAnalogsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml.AnalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnalogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAnalogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        if _grpc_experimental is None:
            raise RuntimeError("grpc.experimental is unavailable in this grpcio runtime")
        return _grpc_experimental.unary_unary(request, target, '/ml.AnalogService/GetAnalogs',
            _GetAnalogsRequest.SerializeToString,
            _GetAnalogsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBatchAnalogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        if _grpc_experimental is None:
            raise RuntimeError("grpc.experimental is unavailable in this grpcio runtime")
        return _grpc_experimental.unary_unary(request, target, '/ml.AnalogService/GetBatchAnalogs',
            _GetBatchAnalogsRequest.SerializeToString,
            _GetBatchAnalogsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
