# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import analogs_pb2 as analogs__pb2


class AnalogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnalogs = channel.unary_unary(
                '/ml.AnalogService/GetAnalogs',
                request_serializer=analogs__pb2.GetAnalogsRequest.SerializeToString,
                response_deserializer=analogs__pb2.GetAnalogsResponse.FromString,
                )
        self.GetBatchAnalogs = channel.unary_unary(
                '/ml.AnalogService/GetBatchAnalogs',
                request_serializer=analogs__pb2.GetBatchAnalogsRequest.SerializeToString,
                response_deserializer=analogs__pb2.GetBatchAnalogsResponse.FromString,
                )
        self.SearchByPhoto = channel.unary_unary(
                '/ml.AnalogService/SearchByPhoto',
                request_serializer=analogs__pb2.SearchByPhotoRequest.SerializeToString,
                response_deserializer=analogs__pb2.SearchByPhotoResponse.FromString,
                )


class AnalogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAnalogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatchAnalogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchByPhoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnalogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalogs,
                    request_deserializer=analogs__pb2.GetAnalogsRequest.FromString,
                    response_serializer=analogs__pb2.GetAnalogsResponse.SerializeToString,
            ),
            'GetBatchAnalogs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatchAnalogs,
                    request_deserializer=analogs__pb2.GetBatchAnalogsRequest.FromString,
                    response_serializer=analogs__pb2.GetBatchAnalogsResponse.SerializeToString,
            ),
            'SearchByPhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchByPhoto,
                    request_deserializer=analogs__pb2.SearchByPhotoRequest.FromString,
                    response_serializer=analogs__pb2.SearchByPhotoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml.AnalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AnalogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAnalogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml.AnalogService/GetAnalogs',
            analogs__pb2.GetAnalogsRequest.SerializeToString,
            analogs__pb2.GetAnalogsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBatchAnalogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml.AnalogService/GetBatchAnalogs',
            analogs__pb2.GetBatchAnalogsRequest.SerializeToString,
            analogs__pb2.GetBatchAnalogsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SearchByPhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ml.AnalogService/SearchByPhoto',
            analogs__pb2.SearchByPhotoRequest.SerializeToString,
            analogs__pb2.SearchByPhotoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
