# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import catalog_pb2 as catalog__pb2

_grpc_experimental = getattr(grpc, "experimental", None)
_ListProductsForMLRequest = getattr(catalog__pb2, "ListProductsForMLRequest")
_ListProductsForMLResponse = getattr(catalog__pb2, "ListProductsForMLResponse")


class CatalogServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListProductsForML = channel.unary_unary(
                '/core.CatalogService/ListProductsForML',
                request_serializer=_ListProductsForMLRequest.SerializeToString,
                response_deserializer=_ListProductsForMLResponse.FromString,
                )


class CatalogServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListProductsForML(self, request, context):
        """Returns all in-stock products with nutrition and active offers.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListProductsForML': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProductsForML,
                    request_deserializer=_ListProductsForMLRequest.FromString,
                    response_serializer=_ListProductsForMLResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'core.CatalogService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CatalogService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListProductsForML(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        if _grpc_experimental is None:
            raise RuntimeError("grpc.experimental is unavailable in this grpcio runtime")
        return _grpc_experimental.unary_unary(request, target, '/core.CatalogService/ListProductsForML',
            _ListProductsForMLRequest.SerializeToString,
            _ListProductsForMLResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
