# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: catalog.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcatalog.proto\x12\x04\x63ore\"\x1a\n\x18ListProductsForMLRequest\"I\n\x19ListProductsForMLResponse\x12,\n\x08products\x18\x01 \x03(\x0b\x32\x1a.core.ProductFeaturesProto\"\xa1\x02\n\x14ProductFeaturesProto\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x13\n\x0b\x63omposition\x18\x04 \x01(\t\x12\x13\n\x0b\x63\x61tegory_id\x18\x05 \x01(\t\x12\x16\n\x0esubcategory_id\x18\x06 \x01(\t\x12\x10\n\x08\x62rand_id\x18\x07 \x01(\t\x12\x0e\n\x06weight\x18\x08 \x01(\t\x12\x10\n\x08\x63\x61lories\x18\t \x01(\x01\x12\x0f\n\x07protein\x18\n \x01(\x01\x12\x0b\n\x03\x66\x61t\x18\x0b \x01(\x01\x12\x15\n\rcarbohydrates\x18\x0c \x01(\x01\x12\'\n\x06offers\x18\r \x03(\x0b\x32\x17.core.ProductOfferBrief\"<\n\x11ProductOfferBrief\x12\x10\n\x08store_id\x18\x01 \x01(\t\x12\x15\n\rprice_kopecks\x18\x02 \x01(\x03\x32\x66\n\x0e\x43\x61talogService\x12T\n\x11ListProductsForML\x12\x1e.core.ListProductsForMLRequest\x1a\x1f.core.ListProductsForMLResponseB\x1fZ\x1dgithub.com/foodsea/proto/coreb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'catalog_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035github.com/foodsea/proto/core'
  _globals['_LISTPRODUCTSFORMLREQUEST']._serialized_start=23
  _globals['_LISTPRODUCTSFORMLREQUEST']._serialized_end=49
  _globals['_LISTPRODUCTSFORMLRESPONSE']._serialized_start=51
  _globals['_LISTPRODUCTSFORMLRESPONSE']._serialized_end=124
  _globals['_PRODUCTFEATURESPROTO']._serialized_start=127
  _globals['_PRODUCTFEATURESPROTO']._serialized_end=416
  _globals['_PRODUCTOFFERBRIEF']._serialized_start=418
  _globals['_PRODUCTOFFERBRIEF']._serialized_end=478
  _globals['_CATALOGSERVICE']._serialized_start=480
  _globals['_CATALOGSERVICE']._serialized_end=582
# @@protoc_insertion_point(module_scope)
