// Code generated by ent, DO NOT EDIT.

package store

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the store type in the database.
	Label = "store"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldLogoURL holds the string denoting the logo_url field in the database.
	FieldLogoURL = "logo_url"
	// FieldIsActive holds the string denoting the is_active field in the database.
	FieldIsActive = "is_active"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeOffers holds the string denoting the offers edge name in mutations.
	EdgeOffers = "offers"
	// EdgeDeliveryCondition holds the string denoting the delivery_condition edge name in mutations.
	EdgeDeliveryCondition = "delivery_condition"
	// Table holds the table name of the store in the database.
	Table = "stores"
	// OffersTable is the table that holds the offers relation/edge.
	OffersTable = "offers"
	// OffersInverseTable is the table name for the Offer entity.
	// It exists in this package in order to avoid circular dependency with the "offer" package.
	OffersInverseTable = "offers"
	// OffersColumn is the table column denoting the offers relation/edge.
	OffersColumn = "store_id"
	// DeliveryConditionTable is the table that holds the delivery_condition relation/edge.
	DeliveryConditionTable = "delivery_conditions"
	// DeliveryConditionInverseTable is the table name for the DeliveryCondition entity.
	// It exists in this package in order to avoid circular dependency with the "deliverycondition" package.
	DeliveryConditionInverseTable = "delivery_conditions"
	// DeliveryConditionColumn is the table column denoting the delivery_condition relation/edge.
	DeliveryConditionColumn = "store_id"
)

// Columns holds all SQL columns for store fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSlug,
	FieldLogoURL,
	FieldIsActive,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// DefaultIsActive holds the default value on creation for the "is_active" field.
	DefaultIsActive bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Store queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByLogoURL orders the results by the logo_url field.
func ByLogoURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogoURL, opts...).ToFunc()
}

// ByIsActive orders the results by the is_active field.
func ByIsActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsActive, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByOffersCount orders the results by offers count.
func ByOffersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newOffersStep(), opts...)
	}
}

// ByOffers orders the results by offers terms.
func ByOffers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOffersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDeliveryConditionField orders the results by delivery_condition field.
func ByDeliveryConditionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeliveryConditionStep(), sql.OrderByField(field, opts...))
	}
}
func newOffersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OffersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, OffersTable, OffersColumn),
	)
}
func newDeliveryConditionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeliveryConditionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, DeliveryConditionTable, DeliveryConditionColumn),
	)
}
