// Code generated by ent, DO NOT EDIT.

package deliverycondition

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the deliverycondition type in the database.
	Label = "delivery_condition"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldStoreID holds the string denoting the store_id field in the database.
	FieldStoreID = "store_id"
	// FieldMinOrderKopecks holds the string denoting the min_order_kopecks field in the database.
	FieldMinOrderKopecks = "min_order_kopecks"
	// FieldDeliveryCostKopecks holds the string denoting the delivery_cost_kopecks field in the database.
	FieldDeliveryCostKopecks = "delivery_cost_kopecks"
	// FieldFreeFromKopecks holds the string denoting the free_from_kopecks field in the database.
	FieldFreeFromKopecks = "free_from_kopecks"
	// FieldEstimatedMinutes holds the string denoting the estimated_minutes field in the database.
	FieldEstimatedMinutes = "estimated_minutes"
	// EdgeStore holds the string denoting the store edge name in mutations.
	EdgeStore = "store"
	// Table holds the table name of the deliverycondition in the database.
	Table = "delivery_conditions"
	// StoreTable is the table that holds the store relation/edge.
	StoreTable = "delivery_conditions"
	// StoreInverseTable is the table name for the Store entity.
	// It exists in this package in order to avoid circular dependency with the "store" package.
	StoreInverseTable = "stores"
	// StoreColumn is the table column denoting the store relation/edge.
	StoreColumn = "store_id"
)

// Columns holds all SQL columns for deliverycondition fields.
var Columns = []string{
	FieldID,
	FieldStoreID,
	FieldMinOrderKopecks,
	FieldDeliveryCostKopecks,
	FieldFreeFromKopecks,
	FieldEstimatedMinutes,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultMinOrderKopecks holds the default value on creation for the "min_order_kopecks" field.
	DefaultMinOrderKopecks int
	// DefaultDeliveryCostKopecks holds the default value on creation for the "delivery_cost_kopecks" field.
	DefaultDeliveryCostKopecks int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the DeliveryCondition queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByStoreID orders the results by the store_id field.
func ByStoreID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStoreID, opts...).ToFunc()
}

// ByMinOrderKopecks orders the results by the min_order_kopecks field.
func ByMinOrderKopecks(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinOrderKopecks, opts...).ToFunc()
}

// ByDeliveryCostKopecks orders the results by the delivery_cost_kopecks field.
func ByDeliveryCostKopecks(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeliveryCostKopecks, opts...).ToFunc()
}

// ByFreeFromKopecks orders the results by the free_from_kopecks field.
func ByFreeFromKopecks(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFreeFromKopecks, opts...).ToFunc()
}

// ByEstimatedMinutes orders the results by the estimated_minutes field.
func ByEstimatedMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEstimatedMinutes, opts...).ToFunc()
}

// ByStoreField orders the results by store field.
func ByStoreField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStoreStep(), sql.OrderByField(field, opts...))
	}
}
func newStoreStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StoreInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, StoreTable, StoreColumn),
	)
}
