// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/foodsea/core/ent/oauthidentity"
	"github.com/foodsea/core/ent/predicate"
	"github.com/foodsea/core/ent/user"
	"github.com/google/uuid"
)

// OAuthIdentityUpdate is the builder for updating OAuthIdentity entities.
type OAuthIdentityUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthIdentityMutation
}

// Where appends a list predicates to the OAuthIdentityUpdate builder.
func (_u *OAuthIdentityUpdate) Where(ps ...predicate.OAuthIdentity) *OAuthIdentityUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthIdentityUpdate) SetUpdatedAt(v time.Time) *OAuthIdentityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *OAuthIdentityUpdate) SetProvider(v string) *OAuthIdentityUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *OAuthIdentityUpdate) SetNillableProvider(v *string) *OAuthIdentityUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderUserID sets the "provider_user_id" field.
func (_u *OAuthIdentityUpdate) SetProviderUserID(v string) *OAuthIdentityUpdate {
	_u.mutation.SetProviderUserID(v)
	return _u
}

// SetNillableProviderUserID sets the "provider_user_id" field if the given value is not nil.
func (_u *OAuthIdentityUpdate) SetNillableProviderUserID(v *string) *OAuthIdentityUpdate {
	if v != nil {
		_u.SetProviderUserID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *OAuthIdentityUpdate) SetEmail(v string) *OAuthIdentityUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *OAuthIdentityUpdate) SetNillableEmail(v *string) *OAuthIdentityUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *OAuthIdentityUpdate) ClearEmail() *OAuthIdentityUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthIdentityUpdate) SetUserID(v uuid.UUID) *OAuthIdentityUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthIdentityUpdate) SetNillableUserID(v *uuid.UUID) *OAuthIdentityUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OAuthIdentityUpdate) SetUser(v *User) *OAuthIdentityUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the OAuthIdentityMutation object of the builder.
func (_u *OAuthIdentityUpdate) Mutation() *OAuthIdentityMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OAuthIdentityUpdate) ClearUser() *OAuthIdentityUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthIdentityUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthIdentityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthIdentityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthIdentityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthIdentityUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if oauthidentity.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized oauthidentity.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := oauthidentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthIdentityUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := oauthidentity.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "OAuthIdentity.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderUserID(); ok {
		if err := oauthidentity.ProviderUserIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_user_id", err: fmt.Errorf(`ent: validator failed for field "OAuthIdentity.provider_user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthIdentity.user"`)
	}
	return nil
}

func (_u *OAuthIdentityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthidentity.Table, oauthidentity.Columns, sqlgraph.NewFieldSpec(oauthidentity.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthidentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(oauthidentity.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderUserID(); ok {
		_spec.SetField(oauthidentity.FieldProviderUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(oauthidentity.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(oauthidentity.FieldEmail, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthidentity.UserTable,
			Columns: []string{oauthidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthidentity.UserTable,
			Columns: []string{oauthidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthidentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthIdentityUpdateOne is the builder for updating a single OAuthIdentity entity.
type OAuthIdentityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthIdentityMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthIdentityUpdateOne) SetUpdatedAt(v time.Time) *OAuthIdentityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProvider sets the "provider" field.
func (_u *OAuthIdentityUpdateOne) SetProvider(v string) *OAuthIdentityUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *OAuthIdentityUpdateOne) SetNillableProvider(v *string) *OAuthIdentityUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderUserID sets the "provider_user_id" field.
func (_u *OAuthIdentityUpdateOne) SetProviderUserID(v string) *OAuthIdentityUpdateOne {
	_u.mutation.SetProviderUserID(v)
	return _u
}

// SetNillableProviderUserID sets the "provider_user_id" field if the given value is not nil.
func (_u *OAuthIdentityUpdateOne) SetNillableProviderUserID(v *string) *OAuthIdentityUpdateOne {
	if v != nil {
		_u.SetProviderUserID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *OAuthIdentityUpdateOne) SetEmail(v string) *OAuthIdentityUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *OAuthIdentityUpdateOne) SetNillableEmail(v *string) *OAuthIdentityUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *OAuthIdentityUpdateOne) ClearEmail() *OAuthIdentityUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OAuthIdentityUpdateOne) SetUserID(v uuid.UUID) *OAuthIdentityUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OAuthIdentityUpdateOne) SetNillableUserID(v *uuid.UUID) *OAuthIdentityUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *OAuthIdentityUpdateOne) SetUser(v *User) *OAuthIdentityUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the OAuthIdentityMutation object of the builder.
func (_u *OAuthIdentityUpdateOne) Mutation() *OAuthIdentityMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *OAuthIdentityUpdateOne) ClearUser() *OAuthIdentityUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the OAuthIdentityUpdate builder.
func (_u *OAuthIdentityUpdateOne) Where(ps ...predicate.OAuthIdentity) *OAuthIdentityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthIdentityUpdateOne) Select(field string, fields ...string) *OAuthIdentityUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthIdentity entity.
func (_u *OAuthIdentityUpdateOne) Save(ctx context.Context) (*OAuthIdentity, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthIdentityUpdateOne) SaveX(ctx context.Context) *OAuthIdentity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthIdentityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthIdentityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthIdentityUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if oauthidentity.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized oauthidentity.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := oauthidentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthIdentityUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := oauthidentity.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "OAuthIdentity.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderUserID(); ok {
		if err := oauthidentity.ProviderUserIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_user_id", err: fmt.Errorf(`ent: validator failed for field "OAuthIdentity.provider_user_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthIdentity.user"`)
	}
	return nil
}

func (_u *OAuthIdentityUpdateOne) sqlSave(ctx context.Context) (_node *OAuthIdentity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthidentity.Table, oauthidentity.Columns, sqlgraph.NewFieldSpec(oauthidentity.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthIdentity.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthidentity.FieldID)
		for _, f := range fields {
			if !oauthidentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthidentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthidentity.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(oauthidentity.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderUserID(); ok {
		_spec.SetField(oauthidentity.FieldProviderUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(oauthidentity.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(oauthidentity.FieldEmail, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthidentity.UserTable,
			Columns: []string{oauthidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthidentity.UserTable,
			Columns: []string{oauthidentity.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OAuthIdentity{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthidentity.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
