// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/foodsea/core/ent/offer"
	"github.com/foodsea/core/ent/product"
	"github.com/foodsea/core/ent/store"
	"github.com/google/uuid"
)

// Offer is the model entity for the Offer schema.
type Offer struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ProductID holds the value of the "product_id" field.
	ProductID uuid.UUID `json:"product_id,omitempty"`
	// StoreID holds the value of the "store_id" field.
	StoreID uuid.UUID `json:"store_id,omitempty"`
	// PriceKopecks holds the value of the "price_kopecks" field.
	PriceKopecks int `json:"price_kopecks,omitempty"`
	// OriginalPriceKopecks holds the value of the "original_price_kopecks" field.
	OriginalPriceKopecks *int `json:"original_price_kopecks,omitempty"`
	// DiscountPercent holds the value of the "discount_percent" field.
	DiscountPercent int8 `json:"discount_percent,omitempty"`
	// InStock holds the value of the "in_stock" field.
	InStock bool `json:"in_stock,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OfferQuery when eager-loading is set.
	Edges        OfferEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OfferEdges holds the relations/edges for other nodes in the graph.
type OfferEdges struct {
	// Product holds the value of the product edge.
	Product *Product `json:"product,omitempty"`
	// Store holds the value of the store edge.
	Store *Store `json:"store,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProductOrErr returns the Product value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OfferEdges) ProductOrErr() (*Product, error) {
	if e.Product != nil {
		return e.Product, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: product.Label}
	}
	return nil, &NotLoadedError{edge: "product"}
}

// StoreOrErr returns the Store value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OfferEdges) StoreOrErr() (*Store, error) {
	if e.Store != nil {
		return e.Store, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: store.Label}
	}
	return nil, &NotLoadedError{edge: "store"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Offer) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case offer.FieldInStock:
			values[i] = new(sql.NullBool)
		case offer.FieldPriceKopecks, offer.FieldOriginalPriceKopecks, offer.FieldDiscountPercent:
			values[i] = new(sql.NullInt64)
		case offer.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case offer.FieldID, offer.FieldProductID, offer.FieldStoreID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Offer fields.
func (_m *Offer) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case offer.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case offer.FieldProductID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field product_id", values[i])
			} else if value != nil {
				_m.ProductID = *value
			}
		case offer.FieldStoreID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field store_id", values[i])
			} else if value != nil {
				_m.StoreID = *value
			}
		case offer.FieldPriceKopecks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_kopecks", values[i])
			} else if value.Valid {
				_m.PriceKopecks = int(value.Int64)
			}
		case offer.FieldOriginalPriceKopecks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field original_price_kopecks", values[i])
			} else if value.Valid {
				_m.OriginalPriceKopecks = new(int)
				*_m.OriginalPriceKopecks = int(value.Int64)
			}
		case offer.FieldDiscountPercent:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field discount_percent", values[i])
			} else if value.Valid {
				_m.DiscountPercent = int8(value.Int64)
			}
		case offer.FieldInStock:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field in_stock", values[i])
			} else if value.Valid {
				_m.InStock = value.Bool
			}
		case offer.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Offer.
// This includes values selected through modifiers, order, etc.
func (_m *Offer) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProduct queries the "product" edge of the Offer entity.
func (_m *Offer) QueryProduct() *ProductQuery {
	return NewOfferClient(_m.config).QueryProduct(_m)
}

// QueryStore queries the "store" edge of the Offer entity.
func (_m *Offer) QueryStore() *StoreQuery {
	return NewOfferClient(_m.config).QueryStore(_m)
}

// Update returns a builder for updating this Offer.
// Note that you need to call Offer.Unwrap() before calling this method if this Offer
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Offer) Update() *OfferUpdateOne {
	return NewOfferClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Offer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Offer) Unwrap() *Offer {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Offer is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Offer) String() string {
	var builder strings.Builder
	builder.WriteString("Offer(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("product_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProductID))
	builder.WriteString(", ")
	builder.WriteString("store_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StoreID))
	builder.WriteString(", ")
	builder.WriteString("price_kopecks=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceKopecks))
	builder.WriteString(", ")
	if v := _m.OriginalPriceKopecks; v != nil {
		builder.WriteString("original_price_kopecks=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("discount_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.DiscountPercent))
	builder.WriteString(", ")
	builder.WriteString("in_stock=")
	builder.WriteString(fmt.Sprintf("%v", _m.InStock))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Offers is a parsable slice of Offer.
type Offers []*Offer
