// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/foodsea/core/ent/orderliveactivity"
	"github.com/foodsea/core/ent/user"
	"github.com/google/uuid"
)

// OrderLiveActivity is the model entity for the OrderLiveActivity schema.
type OrderLiveActivity struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// PushToken holds the value of the "push_token" field.
	PushToken string `json:"push_token,omitempty"`
	// BundleID holds the value of the "bundle_id" field.
	BundleID string `json:"bundle_id,omitempty"`
	// Environment holds the value of the "environment" field.
	Environment orderliveactivity.Environment `json:"environment,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrderLiveActivityQuery when eager-loading is set.
	Edges        OrderLiveActivityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OrderLiveActivityEdges holds the relations/edges for other nodes in the graph.
type OrderLiveActivityEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderLiveActivityEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrderLiveActivity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case orderliveactivity.FieldPushToken, orderliveactivity.FieldBundleID, orderliveactivity.FieldEnvironment:
			values[i] = new(sql.NullString)
		case orderliveactivity.FieldStartedAt, orderliveactivity.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case orderliveactivity.FieldID, orderliveactivity.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrderLiveActivity fields.
func (_m *OrderLiveActivity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case orderliveactivity.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case orderliveactivity.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case orderliveactivity.FieldPushToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field push_token", values[i])
			} else if value.Valid {
				_m.PushToken = value.String
			}
		case orderliveactivity.FieldBundleID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bundle_id", values[i])
			} else if value.Valid {
				_m.BundleID = value.String
			}
		case orderliveactivity.FieldEnvironment:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field environment", values[i])
			} else if value.Valid {
				_m.Environment = orderliveactivity.Environment(value.String)
			}
		case orderliveactivity.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case orderliveactivity.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrderLiveActivity.
// This includes values selected through modifiers, order, etc.
func (_m *OrderLiveActivity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the OrderLiveActivity entity.
func (_m *OrderLiveActivity) QueryUser() *UserQuery {
	return NewOrderLiveActivityClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this OrderLiveActivity.
// Note that you need to call OrderLiveActivity.Unwrap() before calling this method if this OrderLiveActivity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OrderLiveActivity) Update() *OrderLiveActivityUpdateOne {
	return NewOrderLiveActivityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OrderLiveActivity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OrderLiveActivity) Unwrap() *OrderLiveActivity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrderLiveActivity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OrderLiveActivity) String() string {
	var builder strings.Builder
	builder.WriteString("OrderLiveActivity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("push_token=")
	builder.WriteString(_m.PushToken)
	builder.WriteString(", ")
	builder.WriteString("bundle_id=")
	builder.WriteString(_m.BundleID)
	builder.WriteString(", ")
	builder.WriteString("environment=")
	builder.WriteString(fmt.Sprintf("%v", _m.Environment))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OrderLiveActivities is a parsable slice of OrderLiveActivity.
type OrderLiveActivities []*OrderLiveActivity
