// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/foodsea/core/ent/orderliveactivity"
	"github.com/foodsea/core/ent/predicate"
)

// OrderLiveActivityDelete is the builder for deleting a OrderLiveActivity entity.
type OrderLiveActivityDelete struct {
	config
	hooks    []Hook
	mutation *OrderLiveActivityMutation
}

// Where appends a list predicates to the OrderLiveActivityDelete builder.
func (_d *OrderLiveActivityDelete) Where(ps ...predicate.OrderLiveActivity) *OrderLiveActivityDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OrderLiveActivityDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrderLiveActivityDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OrderLiveActivityDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(orderliveactivity.Table, sqlgraph.NewFieldSpec(orderliveactivity.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OrderLiveActivityDeleteOne is the builder for deleting a single OrderLiveActivity entity.
type OrderLiveActivityDeleteOne struct {
	_d *OrderLiveActivityDelete
}

// Where appends a list predicates to the OrderLiveActivityDelete builder.
func (_d *OrderLiveActivityDeleteOne) Where(ps ...predicate.OrderLiveActivity) *OrderLiveActivityDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OrderLiveActivityDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{orderliveactivity.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OrderLiveActivityDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
