// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/foodsea/core/ent/predicate"
	"github.com/foodsea/core/ent/product"
	"github.com/foodsea/core/ent/productnutrition"
	"github.com/google/uuid"
)

// ProductNutritionUpdate is the builder for updating ProductNutrition entities.
type ProductNutritionUpdate struct {
	config
	hooks    []Hook
	mutation *ProductNutritionMutation
}

// Where appends a list predicates to the ProductNutritionUpdate builder.
func (_u *ProductNutritionUpdate) Where(ps ...predicate.ProductNutrition) *ProductNutritionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *ProductNutritionUpdate) SetProductID(v uuid.UUID) *ProductNutritionUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ProductNutritionUpdate) SetNillableProductID(v *uuid.UUID) *ProductNutritionUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetCalories sets the "calories" field.
func (_u *ProductNutritionUpdate) SetCalories(v float64) *ProductNutritionUpdate {
	_u.mutation.ResetCalories()
	_u.mutation.SetCalories(v)
	return _u
}

// SetNillableCalories sets the "calories" field if the given value is not nil.
func (_u *ProductNutritionUpdate) SetNillableCalories(v *float64) *ProductNutritionUpdate {
	if v != nil {
		_u.SetCalories(*v)
	}
	return _u
}

// AddCalories adds value to the "calories" field.
func (_u *ProductNutritionUpdate) AddCalories(v float64) *ProductNutritionUpdate {
	_u.mutation.AddCalories(v)
	return _u
}

// SetProtein sets the "protein" field.
func (_u *ProductNutritionUpdate) SetProtein(v float64) *ProductNutritionUpdate {
	_u.mutation.ResetProtein()
	_u.mutation.SetProtein(v)
	return _u
}

// SetNillableProtein sets the "protein" field if the given value is not nil.
func (_u *ProductNutritionUpdate) SetNillableProtein(v *float64) *ProductNutritionUpdate {
	if v != nil {
		_u.SetProtein(*v)
	}
	return _u
}

// AddProtein adds value to the "protein" field.
func (_u *ProductNutritionUpdate) AddProtein(v float64) *ProductNutritionUpdate {
	_u.mutation.AddProtein(v)
	return _u
}

// SetFat sets the "fat" field.
func (_u *ProductNutritionUpdate) SetFat(v float64) *ProductNutritionUpdate {
	_u.mutation.ResetFat()
	_u.mutation.SetFat(v)
	return _u
}

// SetNillableFat sets the "fat" field if the given value is not nil.
func (_u *ProductNutritionUpdate) SetNillableFat(v *float64) *ProductNutritionUpdate {
	if v != nil {
		_u.SetFat(*v)
	}
	return _u
}

// AddFat adds value to the "fat" field.
func (_u *ProductNutritionUpdate) AddFat(v float64) *ProductNutritionUpdate {
	_u.mutation.AddFat(v)
	return _u
}

// SetCarbohydrates sets the "carbohydrates" field.
func (_u *ProductNutritionUpdate) SetCarbohydrates(v float64) *ProductNutritionUpdate {
	_u.mutation.ResetCarbohydrates()
	_u.mutation.SetCarbohydrates(v)
	return _u
}

// SetNillableCarbohydrates sets the "carbohydrates" field if the given value is not nil.
func (_u *ProductNutritionUpdate) SetNillableCarbohydrates(v *float64) *ProductNutritionUpdate {
	if v != nil {
		_u.SetCarbohydrates(*v)
	}
	return _u
}

// AddCarbohydrates adds value to the "carbohydrates" field.
func (_u *ProductNutritionUpdate) AddCarbohydrates(v float64) *ProductNutritionUpdate {
	_u.mutation.AddCarbohydrates(v)
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *ProductNutritionUpdate) SetProduct(v *Product) *ProductNutritionUpdate {
	return _u.SetProductID(v.ID)
}

// Mutation returns the ProductNutritionMutation object of the builder.
func (_u *ProductNutritionUpdate) Mutation() *ProductNutritionMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *ProductNutritionUpdate) ClearProduct() *ProductNutritionUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProductNutritionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductNutritionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProductNutritionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductNutritionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductNutritionUpdate) check() error {
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProductNutrition.product"`)
	}
	return nil
}

func (_u *ProductNutritionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productnutrition.Table, productnutrition.Columns, sqlgraph.NewFieldSpec(productnutrition.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Calories(); ok {
		_spec.SetField(productnutrition.FieldCalories, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCalories(); ok {
		_spec.AddField(productnutrition.FieldCalories, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Protein(); ok {
		_spec.SetField(productnutrition.FieldProtein, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProtein(); ok {
		_spec.AddField(productnutrition.FieldProtein, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Fat(); ok {
		_spec.SetField(productnutrition.FieldFat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFat(); ok {
		_spec.AddField(productnutrition.FieldFat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Carbohydrates(); ok {
		_spec.SetField(productnutrition.FieldCarbohydrates, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCarbohydrates(); ok {
		_spec.AddField(productnutrition.FieldCarbohydrates, field.TypeFloat64, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   productnutrition.ProductTable,
			Columns: []string{productnutrition.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   productnutrition.ProductTable,
			Columns: []string{productnutrition.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productnutrition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProductNutritionUpdateOne is the builder for updating a single ProductNutrition entity.
type ProductNutritionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProductNutritionMutation
}

// SetProductID sets the "product_id" field.
func (_u *ProductNutritionUpdateOne) SetProductID(v uuid.UUID) *ProductNutritionUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *ProductNutritionUpdateOne) SetNillableProductID(v *uuid.UUID) *ProductNutritionUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetCalories sets the "calories" field.
func (_u *ProductNutritionUpdateOne) SetCalories(v float64) *ProductNutritionUpdateOne {
	_u.mutation.ResetCalories()
	_u.mutation.SetCalories(v)
	return _u
}

// SetNillableCalories sets the "calories" field if the given value is not nil.
func (_u *ProductNutritionUpdateOne) SetNillableCalories(v *float64) *ProductNutritionUpdateOne {
	if v != nil {
		_u.SetCalories(*v)
	}
	return _u
}

// AddCalories adds value to the "calories" field.
func (_u *ProductNutritionUpdateOne) AddCalories(v float64) *ProductNutritionUpdateOne {
	_u.mutation.AddCalories(v)
	return _u
}

// SetProtein sets the "protein" field.
func (_u *ProductNutritionUpdateOne) SetProtein(v float64) *ProductNutritionUpdateOne {
	_u.mutation.ResetProtein()
	_u.mutation.SetProtein(v)
	return _u
}

// SetNillableProtein sets the "protein" field if the given value is not nil.
func (_u *ProductNutritionUpdateOne) SetNillableProtein(v *float64) *ProductNutritionUpdateOne {
	if v != nil {
		_u.SetProtein(*v)
	}
	return _u
}

// AddProtein adds value to the "protein" field.
func (_u *ProductNutritionUpdateOne) AddProtein(v float64) *ProductNutritionUpdateOne {
	_u.mutation.AddProtein(v)
	return _u
}

// SetFat sets the "fat" field.
func (_u *ProductNutritionUpdateOne) SetFat(v float64) *ProductNutritionUpdateOne {
	_u.mutation.ResetFat()
	_u.mutation.SetFat(v)
	return _u
}

// SetNillableFat sets the "fat" field if the given value is not nil.
func (_u *ProductNutritionUpdateOne) SetNillableFat(v *float64) *ProductNutritionUpdateOne {
	if v != nil {
		_u.SetFat(*v)
	}
	return _u
}

// AddFat adds value to the "fat" field.
func (_u *ProductNutritionUpdateOne) AddFat(v float64) *ProductNutritionUpdateOne {
	_u.mutation.AddFat(v)
	return _u
}

// SetCarbohydrates sets the "carbohydrates" field.
func (_u *ProductNutritionUpdateOne) SetCarbohydrates(v float64) *ProductNutritionUpdateOne {
	_u.mutation.ResetCarbohydrates()
	_u.mutation.SetCarbohydrates(v)
	return _u
}

// SetNillableCarbohydrates sets the "carbohydrates" field if the given value is not nil.
func (_u *ProductNutritionUpdateOne) SetNillableCarbohydrates(v *float64) *ProductNutritionUpdateOne {
	if v != nil {
		_u.SetCarbohydrates(*v)
	}
	return _u
}

// AddCarbohydrates adds value to the "carbohydrates" field.
func (_u *ProductNutritionUpdateOne) AddCarbohydrates(v float64) *ProductNutritionUpdateOne {
	_u.mutation.AddCarbohydrates(v)
	return _u
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *ProductNutritionUpdateOne) SetProduct(v *Product) *ProductNutritionUpdateOne {
	return _u.SetProductID(v.ID)
}

// Mutation returns the ProductNutritionMutation object of the builder.
func (_u *ProductNutritionUpdateOne) Mutation() *ProductNutritionMutation {
	return _u.mutation
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *ProductNutritionUpdateOne) ClearProduct() *ProductNutritionUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// Where appends a list predicates to the ProductNutritionUpdate builder.
func (_u *ProductNutritionUpdateOne) Where(ps ...predicate.ProductNutrition) *ProductNutritionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProductNutritionUpdateOne) Select(field string, fields ...string) *ProductNutritionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ProductNutrition entity.
func (_u *ProductNutritionUpdateOne) Save(ctx context.Context) (*ProductNutrition, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProductNutritionUpdateOne) SaveX(ctx context.Context) *ProductNutrition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProductNutritionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProductNutritionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProductNutritionUpdateOne) check() error {
	if _u.mutation.ProductCleared() && len(_u.mutation.ProductIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ProductNutrition.product"`)
	}
	return nil
}

func (_u *ProductNutritionUpdateOne) sqlSave(ctx context.Context) (_node *ProductNutrition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(productnutrition.Table, productnutrition.Columns, sqlgraph.NewFieldSpec(productnutrition.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ProductNutrition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, productnutrition.FieldID)
		for _, f := range fields {
			if !productnutrition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != productnutrition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Calories(); ok {
		_spec.SetField(productnutrition.FieldCalories, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCalories(); ok {
		_spec.AddField(productnutrition.FieldCalories, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Protein(); ok {
		_spec.SetField(productnutrition.FieldProtein, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProtein(); ok {
		_spec.AddField(productnutrition.FieldProtein, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Fat(); ok {
		_spec.SetField(productnutrition.FieldFat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedFat(); ok {
		_spec.AddField(productnutrition.FieldFat, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Carbohydrates(); ok {
		_spec.SetField(productnutrition.FieldCarbohydrates, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCarbohydrates(); ok {
		_spec.AddField(productnutrition.FieldCarbohydrates, field.TypeFloat64, value)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   productnutrition.ProductTable,
			Columns: []string{productnutrition.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   productnutrition.ProductTable,
			Columns: []string{productnutrition.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ProductNutrition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{productnutrition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
