// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: core/catalog.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListProductsForMLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsForMLRequest) Reset() {
	*x = ListProductsForMLRequest{}
	mi := &file_core_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsForMLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsForMLRequest) ProtoMessage() {}

func (x *ListProductsForMLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsForMLRequest.ProtoReflect.Descriptor instead.
func (*ListProductsForMLRequest) Descriptor() ([]byte, []int) {
	return file_core_catalog_proto_rawDescGZIP(), []int{0}
}

type ListProductsForMLResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Products      []*ProductFeaturesProto `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsForMLResponse) Reset() {
	*x = ListProductsForMLResponse{}
	mi := &file_core_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsForMLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsForMLResponse) ProtoMessage() {}

func (x *ListProductsForMLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsForMLResponse.ProtoReflect.Descriptor instead.
func (*ListProductsForMLResponse) Descriptor() ([]byte, []int) {
	return file_core_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *ListProductsForMLResponse) GetProducts() []*ProductFeaturesProto {
	if x != nil {
		return x.Products
	}
	return nil
}

type ProductFeaturesProto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Composition   string                 `protobuf:"bytes,4,opt,name=composition,proto3" json:"composition,omitempty"`
	CategoryId    string                 `protobuf:"bytes,5,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	SubcategoryId string                 `protobuf:"bytes,6,opt,name=subcategory_id,json=subcategoryId,proto3" json:"subcategory_id,omitempty"`
	BrandId       string                 `protobuf:"bytes,7,opt,name=brand_id,json=brandId,proto3" json:"brand_id,omitempty"`
	Weight        string                 `protobuf:"bytes,8,opt,name=weight,proto3" json:"weight,omitempty"`
	Calories      float64                `protobuf:"fixed64,9,opt,name=calories,proto3" json:"calories,omitempty"`
	Protein       float64                `protobuf:"fixed64,10,opt,name=protein,proto3" json:"protein,omitempty"`
	Fat           float64                `protobuf:"fixed64,11,opt,name=fat,proto3" json:"fat,omitempty"`
	Carbohydrates float64                `protobuf:"fixed64,12,opt,name=carbohydrates,proto3" json:"carbohydrates,omitempty"`
	Offers        []*ProductOfferBrief   `protobuf:"bytes,13,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductFeaturesProto) Reset() {
	*x = ProductFeaturesProto{}
	mi := &file_core_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductFeaturesProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductFeaturesProto) ProtoMessage() {}

func (x *ProductFeaturesProto) ProtoReflect() protoreflect.Message {
	mi := &file_core_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductFeaturesProto.ProtoReflect.Descriptor instead.
func (*ProductFeaturesProto) Descriptor() ([]byte, []int) {
	return file_core_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *ProductFeaturesProto) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ProductFeaturesProto) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProductFeaturesProto) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductFeaturesProto) GetComposition() string {
	if x != nil {
		return x.Composition
	}
	return ""
}

func (x *ProductFeaturesProto) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ProductFeaturesProto) GetSubcategoryId() string {
	if x != nil {
		return x.SubcategoryId
	}
	return ""
}

func (x *ProductFeaturesProto) GetBrandId() string {
	if x != nil {
		return x.BrandId
	}
	return ""
}

func (x *ProductFeaturesProto) GetWeight() string {
	if x != nil {
		return x.Weight
	}
	return ""
}

func (x *ProductFeaturesProto) GetCalories() float64 {
	if x != nil {
		return x.Calories
	}
	return 0
}

func (x *ProductFeaturesProto) GetProtein() float64 {
	if x != nil {
		return x.Protein
	}
	return 0
}

func (x *ProductFeaturesProto) GetFat() float64 {
	if x != nil {
		return x.Fat
	}
	return 0
}

func (x *ProductFeaturesProto) GetCarbohydrates() float64 {
	if x != nil {
		return x.Carbohydrates
	}
	return 0
}

func (x *ProductFeaturesProto) GetOffers() []*ProductOfferBrief {
	if x != nil {
		return x.Offers
	}
	return nil
}

type ProductOfferBrief struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	PriceKopecks  int64                  `protobuf:"varint,2,opt,name=price_kopecks,json=priceKopecks,proto3" json:"price_kopecks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductOfferBrief) Reset() {
	*x = ProductOfferBrief{}
	mi := &file_core_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductOfferBrief) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductOfferBrief) ProtoMessage() {}

func (x *ProductOfferBrief) ProtoReflect() protoreflect.Message {
	mi := &file_core_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductOfferBrief.ProtoReflect.Descriptor instead.
func (*ProductOfferBrief) Descriptor() ([]byte, []int) {
	return file_core_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *ProductOfferBrief) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *ProductOfferBrief) GetPriceKopecks() int64 {
	if x != nil {
		return x.PriceKopecks
	}
	return 0
}

var File_core_catalog_proto protoreflect.FileDescriptor

const file_core_catalog_proto_rawDesc = "" +
	"\n" +
	"\x12core/catalog.proto\x12\x04core\"\x1a\n" +
	"\x18ListProductsForMLRequest\"S\n" +
	"\x19ListProductsForMLResponse\x126\n" +
	"\bproducts\x18\x01 \x03(\v2\x1a.core.ProductFeaturesProtoR\bproducts\"\xa7\x03\n" +
	"\x14ProductFeaturesProto\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12 \n" +
	"\vcomposition\x18\x04 \x01(\tR\vcomposition\x12\x1f\n" +
	"\vcategory_id\x18\x05 \x01(\tR\n" +
	"categoryId\x12%\n" +
	"\x0esubcategory_id\x18\x06 \x01(\tR\rsubcategoryId\x12\x19\n" +
	"\bbrand_id\x18\a \x01(\tR\abrandId\x12\x16\n" +
	"\x06weight\x18\b \x01(\tR\x06weight\x12\x1a\n" +
	"\bcalories\x18\t \x01(\x01R\bcalories\x12\x18\n" +
	"\aprotein\x18\n" +
	" \x01(\x01R\aprotein\x12\x10\n" +
	"\x03fat\x18\v \x01(\x01R\x03fat\x12$\n" +
	"\rcarbohydrates\x18\f \x01(\x01R\rcarbohydrates\x12/\n" +
	"\x06offers\x18\r \x03(\v2\x17.core.ProductOfferBriefR\x06offers\"S\n" +
	"\x11ProductOfferBrief\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12#\n" +
	"\rprice_kopecks\x18\x02 \x01(\x03R\fpriceKopecks2f\n" +
	"\x0eCatalogService\x12T\n" +
	"\x11ListProductsForML\x12\x1e.core.ListProductsForMLRequest\x1a\x1f.core.ListProductsForMLResponseB\x1fZ\x1dgithub.com/foodsea/proto/coreb\x06proto3"

var (
	file_core_catalog_proto_rawDescOnce sync.Once
	file_core_catalog_proto_rawDescData []byte
)

func file_core_catalog_proto_rawDescGZIP() []byte {
	file_core_catalog_proto_rawDescOnce.Do(func() {
		file_core_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_catalog_proto_rawDesc), len(file_core_catalog_proto_rawDesc)))
	})
	return file_core_catalog_proto_rawDescData
}

var file_core_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_core_catalog_proto_goTypes = []any{
	(*ListProductsForMLRequest)(nil),  // 0: core.ListProductsForMLRequest
	(*ListProductsForMLResponse)(nil), // 1: core.ListProductsForMLResponse
	(*ProductFeaturesProto)(nil),      // 2: core.ProductFeaturesProto
	(*ProductOfferBrief)(nil),         // 3: core.ProductOfferBrief
}
var file_core_catalog_proto_depIdxs = []int32{
	2, // 0: core.ListProductsForMLResponse.products:type_name -> core.ProductFeaturesProto
	3, // 1: core.ProductFeaturesProto.offers:type_name -> core.ProductOfferBrief
	0, // 2: core.CatalogService.ListProductsForML:input_type -> core.ListProductsForMLRequest
	1, // 3: core.CatalogService.ListProductsForML:output_type -> core.ListProductsForMLResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_catalog_proto_init() }
func file_core_catalog_proto_init() {
	if File_core_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_catalog_proto_rawDesc), len(file_core_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_catalog_proto_goTypes,
		DependencyIndexes: file_core_catalog_proto_depIdxs,
		MessageInfos:      file_core_catalog_proto_msgTypes,
	}.Build()
	File_core_catalog_proto = out.File
	file_core_catalog_proto_goTypes = nil
	file_core_catalog_proto_depIdxs = nil
}
