// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: core/offers.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOffersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductIds    []string               `protobuf:"bytes,1,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffersRequest) Reset() {
	*x = GetOffersRequest{}
	mi := &file_core_offers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffersRequest) ProtoMessage() {}

func (x *GetOffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_offers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffersRequest.ProtoReflect.Descriptor instead.
func (*GetOffersRequest) Descriptor() ([]byte, []int) {
	return file_core_offers_proto_rawDescGZIP(), []int{0}
}

func (x *GetOffersRequest) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type GetOffersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offers        []*OfferProto          `protobuf:"bytes,1,rep,name=offers,proto3" json:"offers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOffersResponse) Reset() {
	*x = GetOffersResponse{}
	mi := &file_core_offers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOffersResponse) ProtoMessage() {}

func (x *GetOffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_offers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOffersResponse.ProtoReflect.Descriptor instead.
func (*GetOffersResponse) Descriptor() ([]byte, []int) {
	return file_core_offers_proto_rawDescGZIP(), []int{1}
}

func (x *GetOffersResponse) GetOffers() []*OfferProto {
	if x != nil {
		return x.Offers
	}
	return nil
}

type OfferProto struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ProductId            string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	StoreId              string                 `protobuf:"bytes,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	StoreName            string                 `protobuf:"bytes,3,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	PriceKopecks         int64                  `protobuf:"varint,4,opt,name=price_kopecks,json=priceKopecks,proto3" json:"price_kopecks,omitempty"`
	OriginalPriceKopecks *int64                 `protobuf:"varint,5,opt,name=original_price_kopecks,json=originalPriceKopecks,proto3,oneof" json:"original_price_kopecks,omitempty"`
	DiscountPercent      int32                  `protobuf:"varint,6,opt,name=discount_percent,json=discountPercent,proto3" json:"discount_percent,omitempty"`
	InStock              bool                   `protobuf:"varint,7,opt,name=in_stock,json=inStock,proto3" json:"in_stock,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *OfferProto) Reset() {
	*x = OfferProto{}
	mi := &file_core_offers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OfferProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OfferProto) ProtoMessage() {}

func (x *OfferProto) ProtoReflect() protoreflect.Message {
	mi := &file_core_offers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OfferProto.ProtoReflect.Descriptor instead.
func (*OfferProto) Descriptor() ([]byte, []int) {
	return file_core_offers_proto_rawDescGZIP(), []int{2}
}

func (x *OfferProto) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OfferProto) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *OfferProto) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *OfferProto) GetPriceKopecks() int64 {
	if x != nil {
		return x.PriceKopecks
	}
	return 0
}

func (x *OfferProto) GetOriginalPriceKopecks() int64 {
	if x != nil && x.OriginalPriceKopecks != nil {
		return *x.OriginalPriceKopecks
	}
	return 0
}

func (x *OfferProto) GetDiscountPercent() int32 {
	if x != nil {
		return x.DiscountPercent
	}
	return 0
}

func (x *OfferProto) GetInStock() bool {
	if x != nil {
		return x.InStock
	}
	return false
}

type GetDeliveryConditionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreIds      []string               `protobuf:"bytes,1,rep,name=store_ids,json=storeIds,proto3" json:"store_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryConditionsRequest) Reset() {
	*x = GetDeliveryConditionsRequest{}
	mi := &file_core_offers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryConditionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryConditionsRequest) ProtoMessage() {}

func (x *GetDeliveryConditionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_offers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryConditionsRequest.ProtoReflect.Descriptor instead.
func (*GetDeliveryConditionsRequest) Descriptor() ([]byte, []int) {
	return file_core_offers_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeliveryConditionsRequest) GetStoreIds() []string {
	if x != nil {
		return x.StoreIds
	}
	return nil
}

type GetDeliveryConditionsResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Conditions    []*DeliveryConditionProto `protobuf:"bytes,1,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeliveryConditionsResponse) Reset() {
	*x = GetDeliveryConditionsResponse{}
	mi := &file_core_offers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeliveryConditionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeliveryConditionsResponse) ProtoMessage() {}

func (x *GetDeliveryConditionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_offers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeliveryConditionsResponse.ProtoReflect.Descriptor instead.
func (*GetDeliveryConditionsResponse) Descriptor() ([]byte, []int) {
	return file_core_offers_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeliveryConditionsResponse) GetConditions() []*DeliveryConditionProto {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type DeliveryConditionProto struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StoreId             string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	MinOrderKopecks     int64                  `protobuf:"varint,2,opt,name=min_order_kopecks,json=minOrderKopecks,proto3" json:"min_order_kopecks,omitempty"`
	DeliveryCostKopecks int64                  `protobuf:"varint,3,opt,name=delivery_cost_kopecks,json=deliveryCostKopecks,proto3" json:"delivery_cost_kopecks,omitempty"`
	FreeFromKopecks     *int64                 `protobuf:"varint,4,opt,name=free_from_kopecks,json=freeFromKopecks,proto3,oneof" json:"free_from_kopecks,omitempty"`
	EstimatedMinutes    *int32                 `protobuf:"varint,5,opt,name=estimated_minutes,json=estimatedMinutes,proto3,oneof" json:"estimated_minutes,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DeliveryConditionProto) Reset() {
	*x = DeliveryConditionProto{}
	mi := &file_core_offers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryConditionProto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryConditionProto) ProtoMessage() {}

func (x *DeliveryConditionProto) ProtoReflect() protoreflect.Message {
	mi := &file_core_offers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryConditionProto.ProtoReflect.Descriptor instead.
func (*DeliveryConditionProto) Descriptor() ([]byte, []int) {
	return file_core_offers_proto_rawDescGZIP(), []int{5}
}

func (x *DeliveryConditionProto) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *DeliveryConditionProto) GetMinOrderKopecks() int64 {
	if x != nil {
		return x.MinOrderKopecks
	}
	return 0
}

func (x *DeliveryConditionProto) GetDeliveryCostKopecks() int64 {
	if x != nil {
		return x.DeliveryCostKopecks
	}
	return 0
}

func (x *DeliveryConditionProto) GetFreeFromKopecks() int64 {
	if x != nil && x.FreeFromKopecks != nil {
		return *x.FreeFromKopecks
	}
	return 0
}

func (x *DeliveryConditionProto) GetEstimatedMinutes() int32 {
	if x != nil && x.EstimatedMinutes != nil {
		return *x.EstimatedMinutes
	}
	return 0
}

var File_core_offers_proto protoreflect.FileDescriptor

const file_core_offers_proto_rawDesc = "" +
	"\n" +
	"\x11core/offers.proto\x12\x04core\"3\n" +
	"\x10GetOffersRequest\x12\x1f\n" +
	"\vproduct_ids\x18\x01 \x03(\tR\n" +
	"productIds\"=\n" +
	"\x11GetOffersResponse\x12(\n" +
	"\x06offers\x18\x01 \x03(\v2\x10.core.OfferProtoR\x06offers\"\xa6\x02\n" +
	"\n" +
	"OfferProto\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\tR\astoreId\x12\x1d\n" +
	"\n" +
	"store_name\x18\x03 \x01(\tR\tstoreName\x12#\n" +
	"\rprice_kopecks\x18\x04 \x01(\x03R\fpriceKopecks\x129\n" +
	"\x16original_price_kopecks\x18\x05 \x01(\x03H\x00R\x14originalPriceKopecks\x88\x01\x01\x12)\n" +
	"\x10discount_percent\x18\x06 \x01(\x05R\x0fdiscountPercent\x12\x19\n" +
	"\bin_stock\x18\a \x01(\bR\ainStockB\x19\n" +
	"\x17_original_price_kopecks\";\n" +
	"\x1cGetDeliveryConditionsRequest\x12\x1b\n" +
	"\tstore_ids\x18\x01 \x03(\tR\bstoreIds\"]\n" +
	"\x1dGetDeliveryConditionsResponse\x12<\n" +
	"\n" +
	"conditions\x18\x01 \x03(\v2\x1c.core.DeliveryConditionProtoR\n" +
	"conditions\"\xa2\x02\n" +
	"\x16DeliveryConditionProto\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12*\n" +
	"\x11min_order_kopecks\x18\x02 \x01(\x03R\x0fminOrderKopecks\x122\n" +
	"\x15delivery_cost_kopecks\x18\x03 \x01(\x03R\x13deliveryCostKopecks\x12/\n" +
	"\x11free_from_kopecks\x18\x04 \x01(\x03H\x00R\x0ffreeFromKopecks\x88\x01\x01\x120\n" +
	"\x11estimated_minutes\x18\x05 \x01(\x05H\x01R\x10estimatedMinutes\x88\x01\x01B\x14\n" +
	"\x12_free_from_kopecksB\x14\n" +
	"\x12_estimated_minutes2\xae\x01\n" +
	"\fOfferService\x12<\n" +
	"\tGetOffers\x12\x16.core.GetOffersRequest\x1a\x17.core.GetOffersResponse\x12`\n" +
	"\x15GetDeliveryConditions\x12\".core.GetDeliveryConditionsRequest\x1a#.core.GetDeliveryConditionsResponseB\x1fZ\x1dgithub.com/foodsea/proto/coreb\x06proto3"

var (
	file_core_offers_proto_rawDescOnce sync.Once
	file_core_offers_proto_rawDescData []byte
)

func file_core_offers_proto_rawDescGZIP() []byte {
	file_core_offers_proto_rawDescOnce.Do(func() {
		file_core_offers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_offers_proto_rawDesc), len(file_core_offers_proto_rawDesc)))
	})
	return file_core_offers_proto_rawDescData
}

var file_core_offers_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_core_offers_proto_goTypes = []any{
	(*GetOffersRequest)(nil),              // 0: core.GetOffersRequest
	(*GetOffersResponse)(nil),             // 1: core.GetOffersResponse
	(*OfferProto)(nil),                    // 2: core.OfferProto
	(*GetDeliveryConditionsRequest)(nil),  // 3: core.GetDeliveryConditionsRequest
	(*GetDeliveryConditionsResponse)(nil), // 4: core.GetDeliveryConditionsResponse
	(*DeliveryConditionProto)(nil),        // 5: core.DeliveryConditionProto
}
var file_core_offers_proto_depIdxs = []int32{
	2, // 0: core.GetOffersResponse.offers:type_name -> core.OfferProto
	5, // 1: core.GetDeliveryConditionsResponse.conditions:type_name -> core.DeliveryConditionProto
	0, // 2: core.OfferService.GetOffers:input_type -> core.GetOffersRequest
	3, // 3: core.OfferService.GetDeliveryConditions:input_type -> core.GetDeliveryConditionsRequest
	1, // 4: core.OfferService.GetOffers:output_type -> core.GetOffersResponse
	4, // 5: core.OfferService.GetDeliveryConditions:output_type -> core.GetDeliveryConditionsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_core_offers_proto_init() }
func file_core_offers_proto_init() {
	if File_core_offers_proto != nil {
		return
	}
	file_core_offers_proto_msgTypes[2].OneofWrappers = []any{}
	file_core_offers_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_offers_proto_rawDesc), len(file_core_offers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_offers_proto_goTypes,
		DependencyIndexes: file_core_offers_proto_depIdxs,
		MessageInfos:      file_core_offers_proto_msgTypes,
	}.Build()
	File_core_offers_proto = out.File
	file_core_offers_proto_goTypes = nil
	file_core_offers_proto_depIdxs = nil
}
