// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/foodsea/ordering/ent/order"
	"github.com/foodsea/ordering/ent/orderitem"
	"github.com/foodsea/ordering/ent/orderstatushistory"
	"github.com/foodsea/ordering/ent/predicate"
	"github.com/foodsea/ordering/ent/sagastate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 4)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   order.Table,
			Columns: order.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: order.FieldID,
			},
		},
		Type: "Order",
		Fields: map[string]*sqlgraph.FieldSpec{
			order.FieldCreatedAt:            {Type: field.TypeTime, Column: order.FieldCreatedAt},
			order.FieldUpdatedAt:            {Type: field.TypeTime, Column: order.FieldUpdatedAt},
			order.FieldUserID:               {Type: field.TypeUUID, Column: order.FieldUserID},
			order.FieldOptimizationResultID: {Type: field.TypeUUID, Column: order.FieldOptimizationResultID},
			order.FieldTotalKopecks:         {Type: field.TypeInt64, Column: order.FieldTotalKopecks},
			order.FieldDeliveryKopecks:      {Type: field.TypeInt64, Column: order.FieldDeliveryKopecks},
			order.FieldStatus:               {Type: field.TypeString, Column: order.FieldStatus},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   orderitem.Table,
			Columns: orderitem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: orderitem.FieldID,
			},
		},
		Type: "OrderItem",
		Fields: map[string]*sqlgraph.FieldSpec{
			orderitem.FieldOrderID:      {Type: field.TypeUUID, Column: orderitem.FieldOrderID},
			orderitem.FieldProductID:    {Type: field.TypeUUID, Column: orderitem.FieldProductID},
			orderitem.FieldProductName:  {Type: field.TypeString, Column: orderitem.FieldProductName},
			orderitem.FieldStoreID:      {Type: field.TypeUUID, Column: orderitem.FieldStoreID},
			orderitem.FieldStoreName:    {Type: field.TypeString, Column: orderitem.FieldStoreName},
			orderitem.FieldQuantity:     {Type: field.TypeInt16, Column: orderitem.FieldQuantity},
			orderitem.FieldPriceKopecks: {Type: field.TypeInt64, Column: orderitem.FieldPriceKopecks},
		},
	}
	graph.Nodes[2] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   orderstatushistory.Table,
			Columns: orderstatushistory.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: orderstatushistory.FieldID,
			},
		},
		Type: "OrderStatusHistory",
		Fields: map[string]*sqlgraph.FieldSpec{
			orderstatushistory.FieldOrderID:   {Type: field.TypeUUID, Column: orderstatushistory.FieldOrderID},
			orderstatushistory.FieldStatus:    {Type: field.TypeString, Column: orderstatushistory.FieldStatus},
			orderstatushistory.FieldComment:   {Type: field.TypeString, Column: orderstatushistory.FieldComment},
			orderstatushistory.FieldChangedAt: {Type: field.TypeTime, Column: orderstatushistory.FieldChangedAt},
		},
	}
	graph.Nodes[3] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   sagastate.Table,
			Columns: sagastate.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: sagastate.FieldID,
			},
		},
		Type: "SagaState",
		Fields: map[string]*sqlgraph.FieldSpec{
			sagastate.FieldCreatedAt:   {Type: field.TypeTime, Column: sagastate.FieldCreatedAt},
			sagastate.FieldUpdatedAt:   {Type: field.TypeTime, Column: sagastate.FieldUpdatedAt},
			sagastate.FieldOrderID:     {Type: field.TypeUUID, Column: sagastate.FieldOrderID},
			sagastate.FieldUserID:      {Type: field.TypeUUID, Column: sagastate.FieldUserID},
			sagastate.FieldCurrentStep: {Type: field.TypeInt8, Column: sagastate.FieldCurrentStep},
			sagastate.FieldStatus:      {Type: field.TypeString, Column: sagastate.FieldStatus},
			sagastate.FieldPayload:     {Type: field.TypeJSON, Column: sagastate.FieldPayload},
		},
	}
	graph.MustAddE(
		"items",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
		},
		"Order",
		"OrderItem",
	)
	graph.MustAddE(
		"history",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.HistoryTable,
			Columns: []string{order.HistoryColumn},
			Bidi:    false,
		},
		"Order",
		"OrderStatusHistory",
	)
	graph.MustAddE(
		"order",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitem.OrderTable,
			Columns: []string{orderitem.OrderColumn},
			Bidi:    false,
		},
		"OrderItem",
		"Order",
	)
	graph.MustAddE(
		"order",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderstatushistory.OrderTable,
			Columns: []string{orderstatushistory.OrderColumn},
			Bidi:    false,
		},
		"OrderStatusHistory",
		"Order",
	)
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *OrderQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the OrderQuery builder.
func (_q *OrderQuery) Filter() *OrderFilter {
	return &OrderFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *OrderMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the OrderMutation builder.
func (m *OrderMutation) Filter() *OrderFilter {
	return &OrderFilter{config: m.config, predicateAdder: m}
}

// OrderFilter provides a generic filtering capability at runtime for OrderQuery.
type OrderFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *OrderFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *OrderFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(order.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *OrderFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(order.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *OrderFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(order.FieldUpdatedAt))
}

// WhereUserID applies the entql [16]byte predicate on the user_id field.
func (f *OrderFilter) WhereUserID(p entql.ValueP) {
	f.Where(p.Field(order.FieldUserID))
}

// WhereOptimizationResultID applies the entql [16]byte predicate on the optimization_result_id field.
func (f *OrderFilter) WhereOptimizationResultID(p entql.ValueP) {
	f.Where(p.Field(order.FieldOptimizationResultID))
}

// WhereTotalKopecks applies the entql int64 predicate on the total_kopecks field.
func (f *OrderFilter) WhereTotalKopecks(p entql.Int64P) {
	f.Where(p.Field(order.FieldTotalKopecks))
}

// WhereDeliveryKopecks applies the entql int64 predicate on the delivery_kopecks field.
func (f *OrderFilter) WhereDeliveryKopecks(p entql.Int64P) {
	f.Where(p.Field(order.FieldDeliveryKopecks))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *OrderFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(order.FieldStatus))
}

// WhereHasItems applies a predicate to check if query has an edge items.
func (f *OrderFilter) WhereHasItems() {
	f.Where(entql.HasEdge("items"))
}

// WhereHasItemsWith applies a predicate to check if query has an edge items with a given conditions (other predicates).
func (f *OrderFilter) WhereHasItemsWith(preds ...predicate.OrderItem) {
	f.Where(entql.HasEdgeWith("items", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasHistory applies a predicate to check if query has an edge history.
func (f *OrderFilter) WhereHasHistory() {
	f.Where(entql.HasEdge("history"))
}

// WhereHasHistoryWith applies a predicate to check if query has an edge history with a given conditions (other predicates).
func (f *OrderFilter) WhereHasHistoryWith(preds ...predicate.OrderStatusHistory) {
	f.Where(entql.HasEdgeWith("history", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *OrderItemQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the OrderItemQuery builder.
func (_q *OrderItemQuery) Filter() *OrderItemFilter {
	return &OrderItemFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *OrderItemMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the OrderItemMutation builder.
func (m *OrderItemMutation) Filter() *OrderItemFilter {
	return &OrderItemFilter{config: m.config, predicateAdder: m}
}

// OrderItemFilter provides a generic filtering capability at runtime for OrderItemQuery.
type OrderItemFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *OrderItemFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *OrderItemFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(orderitem.FieldID))
}

// WhereOrderID applies the entql [16]byte predicate on the order_id field.
func (f *OrderItemFilter) WhereOrderID(p entql.ValueP) {
	f.Where(p.Field(orderitem.FieldOrderID))
}

// WhereProductID applies the entql [16]byte predicate on the product_id field.
func (f *OrderItemFilter) WhereProductID(p entql.ValueP) {
	f.Where(p.Field(orderitem.FieldProductID))
}

// WhereProductName applies the entql string predicate on the product_name field.
func (f *OrderItemFilter) WhereProductName(p entql.StringP) {
	f.Where(p.Field(orderitem.FieldProductName))
}

// WhereStoreID applies the entql [16]byte predicate on the store_id field.
func (f *OrderItemFilter) WhereStoreID(p entql.ValueP) {
	f.Where(p.Field(orderitem.FieldStoreID))
}

// WhereStoreName applies the entql string predicate on the store_name field.
func (f *OrderItemFilter) WhereStoreName(p entql.StringP) {
	f.Where(p.Field(orderitem.FieldStoreName))
}

// WhereQuantity applies the entql int16 predicate on the quantity field.
func (f *OrderItemFilter) WhereQuantity(p entql.Int16P) {
	f.Where(p.Field(orderitem.FieldQuantity))
}

// WherePriceKopecks applies the entql int64 predicate on the price_kopecks field.
func (f *OrderItemFilter) WherePriceKopecks(p entql.Int64P) {
	f.Where(p.Field(orderitem.FieldPriceKopecks))
}

// WhereHasOrder applies a predicate to check if query has an edge order.
func (f *OrderItemFilter) WhereHasOrder() {
	f.Where(entql.HasEdge("order"))
}

// WhereHasOrderWith applies a predicate to check if query has an edge order with a given conditions (other predicates).
func (f *OrderItemFilter) WhereHasOrderWith(preds ...predicate.Order) {
	f.Where(entql.HasEdgeWith("order", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *OrderStatusHistoryQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the OrderStatusHistoryQuery builder.
func (_q *OrderStatusHistoryQuery) Filter() *OrderStatusHistoryFilter {
	return &OrderStatusHistoryFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *OrderStatusHistoryMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the OrderStatusHistoryMutation builder.
func (m *OrderStatusHistoryMutation) Filter() *OrderStatusHistoryFilter {
	return &OrderStatusHistoryFilter{config: m.config, predicateAdder: m}
}

// OrderStatusHistoryFilter provides a generic filtering capability at runtime for OrderStatusHistoryQuery.
type OrderStatusHistoryFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *OrderStatusHistoryFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[2].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *OrderStatusHistoryFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(orderstatushistory.FieldID))
}

// WhereOrderID applies the entql [16]byte predicate on the order_id field.
func (f *OrderStatusHistoryFilter) WhereOrderID(p entql.ValueP) {
	f.Where(p.Field(orderstatushistory.FieldOrderID))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *OrderStatusHistoryFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(orderstatushistory.FieldStatus))
}

// WhereComment applies the entql string predicate on the comment field.
func (f *OrderStatusHistoryFilter) WhereComment(p entql.StringP) {
	f.Where(p.Field(orderstatushistory.FieldComment))
}

// WhereChangedAt applies the entql time.Time predicate on the changed_at field.
func (f *OrderStatusHistoryFilter) WhereChangedAt(p entql.TimeP) {
	f.Where(p.Field(orderstatushistory.FieldChangedAt))
}

// WhereHasOrder applies a predicate to check if query has an edge order.
func (f *OrderStatusHistoryFilter) WhereHasOrder() {
	f.Where(entql.HasEdge("order"))
}

// WhereHasOrderWith applies a predicate to check if query has an edge order with a given conditions (other predicates).
func (f *OrderStatusHistoryFilter) WhereHasOrderWith(preds ...predicate.Order) {
	f.Where(entql.HasEdgeWith("order", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *SagaStateQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the SagaStateQuery builder.
func (_q *SagaStateQuery) Filter() *SagaStateFilter {
	return &SagaStateFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *SagaStateMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the SagaStateMutation builder.
func (m *SagaStateMutation) Filter() *SagaStateFilter {
	return &SagaStateFilter{config: m.config, predicateAdder: m}
}

// SagaStateFilter provides a generic filtering capability at runtime for SagaStateQuery.
type SagaStateFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *SagaStateFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[3].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *SagaStateFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(sagastate.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *SagaStateFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(sagastate.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *SagaStateFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(sagastate.FieldUpdatedAt))
}

// WhereOrderID applies the entql [16]byte predicate on the order_id field.
func (f *SagaStateFilter) WhereOrderID(p entql.ValueP) {
	f.Where(p.Field(sagastate.FieldOrderID))
}

// WhereUserID applies the entql [16]byte predicate on the user_id field.
func (f *SagaStateFilter) WhereUserID(p entql.ValueP) {
	f.Where(p.Field(sagastate.FieldUserID))
}

// WhereCurrentStep applies the entql int8 predicate on the current_step field.
func (f *SagaStateFilter) WhereCurrentStep(p entql.Int8P) {
	f.Where(p.Field(sagastate.FieldCurrentStep))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *SagaStateFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(sagastate.FieldStatus))
}

// WherePayload applies the entql json.RawMessage predicate on the payload field.
func (f *SagaStateFilter) WherePayload(p entql.BytesP) {
	f.Where(p.Field(sagastate.FieldPayload))
}
