// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/foodsea/ordering/ent/order"
	"github.com/foodsea/ordering/ent/orderstatushistory"
	"github.com/foodsea/ordering/ent/predicate"
	"github.com/google/uuid"
)

// OrderStatusHistoryUpdate is the builder for updating OrderStatusHistory entities.
type OrderStatusHistoryUpdate struct {
	config
	hooks    []Hook
	mutation *OrderStatusHistoryMutation
}

// Where appends a list predicates to the OrderStatusHistoryUpdate builder.
func (_u *OrderStatusHistoryUpdate) Where(ps ...predicate.OrderStatusHistory) *OrderStatusHistoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *OrderStatusHistoryUpdate) SetOrderID(v uuid.UUID) *OrderStatusHistoryUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *OrderStatusHistoryUpdate) SetNillableOrderID(v *uuid.UUID) *OrderStatusHistoryUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderStatusHistoryUpdate) SetStatus(v string) *OrderStatusHistoryUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderStatusHistoryUpdate) SetNillableStatus(v *string) *OrderStatusHistoryUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *OrderStatusHistoryUpdate) SetComment(v string) *OrderStatusHistoryUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *OrderStatusHistoryUpdate) SetNillableComment(v *string) *OrderStatusHistoryUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *OrderStatusHistoryUpdate) ClearComment() *OrderStatusHistoryUpdate {
	_u.mutation.ClearComment()
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *OrderStatusHistoryUpdate) SetOrder(v *Order) *OrderStatusHistoryUpdate {
	return _u.SetOrderID(v.ID)
}

// Mutation returns the OrderStatusHistoryMutation object of the builder.
func (_u *OrderStatusHistoryUpdate) Mutation() *OrderStatusHistoryMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *OrderStatusHistoryUpdate) ClearOrder() *OrderStatusHistoryUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderStatusHistoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderStatusHistoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderStatusHistoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderStatusHistoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderStatusHistoryUpdate) check() error {
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderStatusHistory.order"`)
	}
	return nil
}

func (_u *OrderStatusHistoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderstatushistory.Table, orderstatushistory.Columns, sqlgraph.NewFieldSpec(orderstatushistory.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(orderstatushistory.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(orderstatushistory.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(orderstatushistory.FieldComment, field.TypeString)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderstatushistory.OrderTable,
			Columns: []string{orderstatushistory.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderstatushistory.OrderTable,
			Columns: []string{orderstatushistory.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderstatushistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderStatusHistoryUpdateOne is the builder for updating a single OrderStatusHistory entity.
type OrderStatusHistoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderStatusHistoryMutation
}

// SetOrderID sets the "order_id" field.
func (_u *OrderStatusHistoryUpdateOne) SetOrderID(v uuid.UUID) *OrderStatusHistoryUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *OrderStatusHistoryUpdateOne) SetNillableOrderID(v *uuid.UUID) *OrderStatusHistoryUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrderStatusHistoryUpdateOne) SetStatus(v string) *OrderStatusHistoryUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrderStatusHistoryUpdateOne) SetNillableStatus(v *string) *OrderStatusHistoryUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetComment sets the "comment" field.
func (_u *OrderStatusHistoryUpdateOne) SetComment(v string) *OrderStatusHistoryUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *OrderStatusHistoryUpdateOne) SetNillableComment(v *string) *OrderStatusHistoryUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *OrderStatusHistoryUpdateOne) ClearComment() *OrderStatusHistoryUpdateOne {
	_u.mutation.ClearComment()
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *OrderStatusHistoryUpdateOne) SetOrder(v *Order) *OrderStatusHistoryUpdateOne {
	return _u.SetOrderID(v.ID)
}

// Mutation returns the OrderStatusHistoryMutation object of the builder.
func (_u *OrderStatusHistoryUpdateOne) Mutation() *OrderStatusHistoryMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *OrderStatusHistoryUpdateOne) ClearOrder() *OrderStatusHistoryUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// Where appends a list predicates to the OrderStatusHistoryUpdate builder.
func (_u *OrderStatusHistoryUpdateOne) Where(ps ...predicate.OrderStatusHistory) *OrderStatusHistoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderStatusHistoryUpdateOne) Select(field string, fields ...string) *OrderStatusHistoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrderStatusHistory entity.
func (_u *OrderStatusHistoryUpdateOne) Save(ctx context.Context) (*OrderStatusHistory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderStatusHistoryUpdateOne) SaveX(ctx context.Context) *OrderStatusHistory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderStatusHistoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderStatusHistoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderStatusHistoryUpdateOne) check() error {
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderStatusHistory.order"`)
	}
	return nil
}

func (_u *OrderStatusHistoryUpdateOne) sqlSave(ctx context.Context) (_node *OrderStatusHistory, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderstatushistory.Table, orderstatushistory.Columns, sqlgraph.NewFieldSpec(orderstatushistory.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderStatusHistory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderstatushistory.FieldID)
		for _, f := range fields {
			if !orderstatushistory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderstatushistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(orderstatushistory.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(orderstatushistory.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(orderstatushistory.FieldComment, field.TypeString)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderstatushistory.OrderTable,
			Columns: []string{orderstatushistory.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderstatushistory.OrderTable,
			Columns: []string{orderstatushistory.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrderStatusHistory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderstatushistory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
