// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/foodsea/ordering/ent/order"
	"github.com/foodsea/ordering/ent/orderitem"
	"github.com/foodsea/ordering/ent/predicate"
	"github.com/google/uuid"
)

// OrderItemUpdate is the builder for updating OrderItem entities.
type OrderItemUpdate struct {
	config
	hooks    []Hook
	mutation *OrderItemMutation
}

// Where appends a list predicates to the OrderItemUpdate builder.
func (_u *OrderItemUpdate) Where(ps ...predicate.OrderItem) *OrderItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *OrderItemUpdate) SetOrderID(v uuid.UUID) *OrderItemUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *OrderItemUpdate) SetNillableOrderID(v *uuid.UUID) *OrderItemUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *OrderItemUpdate) SetProductID(v uuid.UUID) *OrderItemUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *OrderItemUpdate) SetNillableProductID(v *uuid.UUID) *OrderItemUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *OrderItemUpdate) SetProductName(v string) *OrderItemUpdate {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *OrderItemUpdate) SetNillableProductName(v *string) *OrderItemUpdate {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetStoreID sets the "store_id" field.
func (_u *OrderItemUpdate) SetStoreID(v uuid.UUID) *OrderItemUpdate {
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *OrderItemUpdate) SetNillableStoreID(v *uuid.UUID) *OrderItemUpdate {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// SetStoreName sets the "store_name" field.
func (_u *OrderItemUpdate) SetStoreName(v string) *OrderItemUpdate {
	_u.mutation.SetStoreName(v)
	return _u
}

// SetNillableStoreName sets the "store_name" field if the given value is not nil.
func (_u *OrderItemUpdate) SetNillableStoreName(v *string) *OrderItemUpdate {
	if v != nil {
		_u.SetStoreName(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OrderItemUpdate) SetQuantity(v int16) *OrderItemUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderItemUpdate) SetNillableQuantity(v *int16) *OrderItemUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OrderItemUpdate) AddQuantity(v int16) *OrderItemUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetPriceKopecks sets the "price_kopecks" field.
func (_u *OrderItemUpdate) SetPriceKopecks(v int64) *OrderItemUpdate {
	_u.mutation.ResetPriceKopecks()
	_u.mutation.SetPriceKopecks(v)
	return _u
}

// SetNillablePriceKopecks sets the "price_kopecks" field if the given value is not nil.
func (_u *OrderItemUpdate) SetNillablePriceKopecks(v *int64) *OrderItemUpdate {
	if v != nil {
		_u.SetPriceKopecks(*v)
	}
	return _u
}

// AddPriceKopecks adds value to the "price_kopecks" field.
func (_u *OrderItemUpdate) AddPriceKopecks(v int64) *OrderItemUpdate {
	_u.mutation.AddPriceKopecks(v)
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *OrderItemUpdate) SetOrder(v *Order) *OrderItemUpdate {
	return _u.SetOrderID(v.ID)
}

// Mutation returns the OrderItemMutation object of the builder.
func (_u *OrderItemUpdate) Mutation() *OrderItemMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *OrderItemUpdate) ClearOrder() *OrderItemUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderItemUpdate) check() error {
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderItem.order"`)
	}
	return nil
}

func (_u *OrderItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderitem.Table, orderitem.Columns, sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(orderitem.FieldProductID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(orderitem.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StoreID(); ok {
		_spec.SetField(orderitem.FieldStoreID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.StoreName(); ok {
		_spec.SetField(orderitem.FieldStoreName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(orderitem.FieldQuantity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(orderitem.FieldQuantity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.PriceKopecks(); ok {
		_spec.SetField(orderitem.FieldPriceKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPriceKopecks(); ok {
		_spec.AddField(orderitem.FieldPriceKopecks, field.TypeInt64, value)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitem.OrderTable,
			Columns: []string{orderitem.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitem.OrderTable,
			Columns: []string{orderitem.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderItemUpdateOne is the builder for updating a single OrderItem entity.
type OrderItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderItemMutation
}

// SetOrderID sets the "order_id" field.
func (_u *OrderItemUpdateOne) SetOrderID(v uuid.UUID) *OrderItemUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *OrderItemUpdateOne) SetNillableOrderID(v *uuid.UUID) *OrderItemUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *OrderItemUpdateOne) SetProductID(v uuid.UUID) *OrderItemUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *OrderItemUpdateOne) SetNillableProductID(v *uuid.UUID) *OrderItemUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *OrderItemUpdateOne) SetProductName(v string) *OrderItemUpdateOne {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *OrderItemUpdateOne) SetNillableProductName(v *string) *OrderItemUpdateOne {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetStoreID sets the "store_id" field.
func (_u *OrderItemUpdateOne) SetStoreID(v uuid.UUID) *OrderItemUpdateOne {
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *OrderItemUpdateOne) SetNillableStoreID(v *uuid.UUID) *OrderItemUpdateOne {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// SetStoreName sets the "store_name" field.
func (_u *OrderItemUpdateOne) SetStoreName(v string) *OrderItemUpdateOne {
	_u.mutation.SetStoreName(v)
	return _u
}

// SetNillableStoreName sets the "store_name" field if the given value is not nil.
func (_u *OrderItemUpdateOne) SetNillableStoreName(v *string) *OrderItemUpdateOne {
	if v != nil {
		_u.SetStoreName(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OrderItemUpdateOne) SetQuantity(v int16) *OrderItemUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderItemUpdateOne) SetNillableQuantity(v *int16) *OrderItemUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OrderItemUpdateOne) AddQuantity(v int16) *OrderItemUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetPriceKopecks sets the "price_kopecks" field.
func (_u *OrderItemUpdateOne) SetPriceKopecks(v int64) *OrderItemUpdateOne {
	_u.mutation.ResetPriceKopecks()
	_u.mutation.SetPriceKopecks(v)
	return _u
}

// SetNillablePriceKopecks sets the "price_kopecks" field if the given value is not nil.
func (_u *OrderItemUpdateOne) SetNillablePriceKopecks(v *int64) *OrderItemUpdateOne {
	if v != nil {
		_u.SetPriceKopecks(*v)
	}
	return _u
}

// AddPriceKopecks adds value to the "price_kopecks" field.
func (_u *OrderItemUpdateOne) AddPriceKopecks(v int64) *OrderItemUpdateOne {
	_u.mutation.AddPriceKopecks(v)
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *OrderItemUpdateOne) SetOrder(v *Order) *OrderItemUpdateOne {
	return _u.SetOrderID(v.ID)
}

// Mutation returns the OrderItemMutation object of the builder.
func (_u *OrderItemUpdateOne) Mutation() *OrderItemMutation {
	return _u.mutation
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *OrderItemUpdateOne) ClearOrder() *OrderItemUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// Where appends a list predicates to the OrderItemUpdate builder.
func (_u *OrderItemUpdateOne) Where(ps ...predicate.OrderItem) *OrderItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderItemUpdateOne) Select(field string, fields ...string) *OrderItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrderItem entity.
func (_u *OrderItemUpdateOne) Save(ctx context.Context) (*OrderItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderItemUpdateOne) SaveX(ctx context.Context) *OrderItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrderItemUpdateOne) check() error {
	if _u.mutation.OrderCleared() && len(_u.mutation.OrderIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OrderItem.order"`)
	}
	return nil
}

func (_u *OrderItemUpdateOne) sqlSave(ctx context.Context) (_node *OrderItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(orderitem.Table, orderitem.Columns, sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, orderitem.FieldID)
		for _, f := range fields {
			if !orderitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != orderitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(orderitem.FieldProductID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(orderitem.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StoreID(); ok {
		_spec.SetField(orderitem.FieldStoreID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.StoreName(); ok {
		_spec.SetField(orderitem.FieldStoreName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(orderitem.FieldQuantity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(orderitem.FieldQuantity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.PriceKopecks(); ok {
		_spec.SetField(orderitem.FieldPriceKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPriceKopecks(); ok {
		_spec.AddField(orderitem.FieldPriceKopecks, field.TypeInt64, value)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitem.OrderTable,
			Columns: []string{orderitem.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderitem.OrderTable,
			Columns: []string{orderitem.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrderItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{orderitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
