// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/foodsea/ordering/ent/order"
	"github.com/foodsea/ordering/ent/orderstatushistory"
	"github.com/google/uuid"
)

// OrderStatusHistoryCreate is the builder for creating a OrderStatusHistory entity.
type OrderStatusHistoryCreate struct {
	config
	mutation *OrderStatusHistoryMutation
	hooks    []Hook
}

// SetOrderID sets the "order_id" field.
func (_c *OrderStatusHistoryCreate) SetOrderID(v uuid.UUID) *OrderStatusHistoryCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *OrderStatusHistoryCreate) SetStatus(v string) *OrderStatusHistoryCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetComment sets the "comment" field.
func (_c *OrderStatusHistoryCreate) SetComment(v string) *OrderStatusHistoryCreate {
	_c.mutation.SetComment(v)
	return _c
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_c *OrderStatusHistoryCreate) SetNillableComment(v *string) *OrderStatusHistoryCreate {
	if v != nil {
		_c.SetComment(*v)
	}
	return _c
}

// SetChangedAt sets the "changed_at" field.
func (_c *OrderStatusHistoryCreate) SetChangedAt(v time.Time) *OrderStatusHistoryCreate {
	_c.mutation.SetChangedAt(v)
	return _c
}

// SetNillableChangedAt sets the "changed_at" field if the given value is not nil.
func (_c *OrderStatusHistoryCreate) SetNillableChangedAt(v *time.Time) *OrderStatusHistoryCreate {
	if v != nil {
		_c.SetChangedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OrderStatusHistoryCreate) SetID(v uuid.UUID) *OrderStatusHistoryCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OrderStatusHistoryCreate) SetNillableID(v *uuid.UUID) *OrderStatusHistoryCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetOrder sets the "order" edge to the Order entity.
func (_c *OrderStatusHistoryCreate) SetOrder(v *Order) *OrderStatusHistoryCreate {
	return _c.SetOrderID(v.ID)
}

// Mutation returns the OrderStatusHistoryMutation object of the builder.
func (_c *OrderStatusHistoryCreate) Mutation() *OrderStatusHistoryMutation {
	return _c.mutation
}

// Save creates the OrderStatusHistory in the database.
func (_c *OrderStatusHistoryCreate) Save(ctx context.Context) (*OrderStatusHistory, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderStatusHistoryCreate) SaveX(ctx context.Context) *OrderStatusHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderStatusHistoryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderStatusHistoryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrderStatusHistoryCreate) defaults() {
	if _, ok := _c.mutation.ChangedAt(); !ok {
		v := orderstatushistory.DefaultChangedAt()
		_c.mutation.SetChangedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := orderstatushistory.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderStatusHistoryCreate) check() error {
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "OrderStatusHistory.order_id"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OrderStatusHistory.status"`)}
	}
	if _, ok := _c.mutation.ChangedAt(); !ok {
		return &ValidationError{Name: "changed_at", err: errors.New(`ent: missing required field "OrderStatusHistory.changed_at"`)}
	}
	if len(_c.mutation.OrderIDs()) == 0 {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required edge "OrderStatusHistory.order"`)}
	}
	return nil
}

func (_c *OrderStatusHistoryCreate) sqlSave(ctx context.Context) (*OrderStatusHistory, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderStatusHistoryCreate) createSpec() (*OrderStatusHistory, *sqlgraph.CreateSpec) {
	var (
		_node = &OrderStatusHistory{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(orderstatushistory.Table, sqlgraph.NewFieldSpec(orderstatushistory.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(orderstatushistory.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Comment(); ok {
		_spec.SetField(orderstatushistory.FieldComment, field.TypeString, value)
		_node.Comment = &value
	}
	if value, ok := _c.mutation.ChangedAt(); ok {
		_spec.SetField(orderstatushistory.FieldChangedAt, field.TypeTime, value)
		_node.ChangedAt = value
	}
	if nodes := _c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   orderstatushistory.OrderTable,
			Columns: []string{orderstatushistory.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OrderID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrderStatusHistoryCreateBulk is the builder for creating many OrderStatusHistory entities in bulk.
type OrderStatusHistoryCreateBulk struct {
	config
	err      error
	builders []*OrderStatusHistoryCreate
}

// Save creates the OrderStatusHistory entities in the database.
func (_c *OrderStatusHistoryCreateBulk) Save(ctx context.Context) ([]*OrderStatusHistory, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrderStatusHistory, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderStatusHistoryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderStatusHistoryCreateBulk) SaveX(ctx context.Context) []*OrderStatusHistory {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderStatusHistoryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderStatusHistoryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
