// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/foodsea/ordering/ent/predicate"
	"github.com/foodsea/ordering/ent/sagastate"
	"github.com/google/uuid"
)

// SagaStateUpdate is the builder for updating SagaState entities.
type SagaStateUpdate struct {
	config
	hooks    []Hook
	mutation *SagaStateMutation
}

// Where appends a list predicates to the SagaStateUpdate builder.
func (_u *SagaStateUpdate) Where(ps ...predicate.SagaState) *SagaStateUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SagaStateUpdate) SetUpdatedAt(v time.Time) *SagaStateUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *SagaStateUpdate) SetOrderID(v uuid.UUID) *SagaStateUpdate {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *SagaStateUpdate) SetNillableOrderID(v *uuid.UUID) *SagaStateUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SagaStateUpdate) SetUserID(v uuid.UUID) *SagaStateUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SagaStateUpdate) SetNillableUserID(v *uuid.UUID) *SagaStateUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCurrentStep sets the "current_step" field.
func (_u *SagaStateUpdate) SetCurrentStep(v int8) *SagaStateUpdate {
	_u.mutation.ResetCurrentStep()
	_u.mutation.SetCurrentStep(v)
	return _u
}

// SetNillableCurrentStep sets the "current_step" field if the given value is not nil.
func (_u *SagaStateUpdate) SetNillableCurrentStep(v *int8) *SagaStateUpdate {
	if v != nil {
		_u.SetCurrentStep(*v)
	}
	return _u
}

// AddCurrentStep adds value to the "current_step" field.
func (_u *SagaStateUpdate) AddCurrentStep(v int8) *SagaStateUpdate {
	_u.mutation.AddCurrentStep(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SagaStateUpdate) SetStatus(v string) *SagaStateUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SagaStateUpdate) SetNillableStatus(v *string) *SagaStateUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *SagaStateUpdate) SetPayload(v map[string]interface{}) *SagaStateUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// Mutation returns the SagaStateMutation object of the builder.
func (_u *SagaStateUpdate) Mutation() *SagaStateMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SagaStateUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SagaStateUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SagaStateUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SagaStateUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SagaStateUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if sagastate.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sagastate.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sagastate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (_u *SagaStateUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(sagastate.Table, sagastate.Columns, sqlgraph.NewFieldSpec(sagastate.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sagastate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(sagastate.FieldOrderID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(sagastate.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.CurrentStep(); ok {
		_spec.SetField(sagastate.FieldCurrentStep, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedCurrentStep(); ok {
		_spec.AddField(sagastate.FieldCurrentStep, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sagastate.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(sagastate.FieldPayload, field.TypeJSON, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sagastate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SagaStateUpdateOne is the builder for updating a single SagaState entity.
type SagaStateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SagaStateMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SagaStateUpdateOne) SetUpdatedAt(v time.Time) *SagaStateUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *SagaStateUpdateOne) SetOrderID(v uuid.UUID) *SagaStateUpdateOne {
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *SagaStateUpdateOne) SetNillableOrderID(v *uuid.UUID) *SagaStateUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SagaStateUpdateOne) SetUserID(v uuid.UUID) *SagaStateUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SagaStateUpdateOne) SetNillableUserID(v *uuid.UUID) *SagaStateUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCurrentStep sets the "current_step" field.
func (_u *SagaStateUpdateOne) SetCurrentStep(v int8) *SagaStateUpdateOne {
	_u.mutation.ResetCurrentStep()
	_u.mutation.SetCurrentStep(v)
	return _u
}

// SetNillableCurrentStep sets the "current_step" field if the given value is not nil.
func (_u *SagaStateUpdateOne) SetNillableCurrentStep(v *int8) *SagaStateUpdateOne {
	if v != nil {
		_u.SetCurrentStep(*v)
	}
	return _u
}

// AddCurrentStep adds value to the "current_step" field.
func (_u *SagaStateUpdateOne) AddCurrentStep(v int8) *SagaStateUpdateOne {
	_u.mutation.AddCurrentStep(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *SagaStateUpdateOne) SetStatus(v string) *SagaStateUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SagaStateUpdateOne) SetNillableStatus(v *string) *SagaStateUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *SagaStateUpdateOne) SetPayload(v map[string]interface{}) *SagaStateUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// Mutation returns the SagaStateMutation object of the builder.
func (_u *SagaStateUpdateOne) Mutation() *SagaStateMutation {
	return _u.mutation
}

// Where appends a list predicates to the SagaStateUpdate builder.
func (_u *SagaStateUpdateOne) Where(ps ...predicate.SagaState) *SagaStateUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SagaStateUpdateOne) Select(field string, fields ...string) *SagaStateUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SagaState entity.
func (_u *SagaStateUpdateOne) Save(ctx context.Context) (*SagaState, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SagaStateUpdateOne) SaveX(ctx context.Context) *SagaState {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SagaStateUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SagaStateUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SagaStateUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if sagastate.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sagastate.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sagastate.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (_u *SagaStateUpdateOne) sqlSave(ctx context.Context) (_node *SagaState, err error) {
	_spec := sqlgraph.NewUpdateSpec(sagastate.Table, sagastate.Columns, sqlgraph.NewFieldSpec(sagastate.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SagaState.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sagastate.FieldID)
		for _, f := range fields {
			if !sagastate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sagastate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sagastate.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(sagastate.FieldOrderID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(sagastate.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.CurrentStep(); ok {
		_spec.SetField(sagastate.FieldCurrentStep, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedCurrentStep(); ok {
		_spec.AddField(sagastate.FieldCurrentStep, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sagastate.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(sagastate.FieldPayload, field.TypeJSON, value)
	}
	_node = &SagaState{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sagastate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
