apiVersion: v1
kind: Secret
metadata:
  name: ordering-secrets
  namespace: foodsea
type: Opaque
stringData:
  DB_URL: postgres://postgres:changeme@ordering-postgres:5432/ordering_db?sslmode=require
  DB_USER: postgres
  DB_PASSWORD: changeme
  JWT_SECRET: change-me-in-production
