// Code generated by ent, DO NOT EDIT.

package userdevice

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userdevice type in the database.
	Label = "user_device"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldApnsToken holds the string denoting the apns_token field in the database.
	FieldApnsToken = "apns_token"
	// FieldBundleID holds the string denoting the bundle_id field in the database.
	FieldBundleID = "bundle_id"
	// FieldEnvironment holds the string denoting the environment field in the database.
	FieldEnvironment = "environment"
	// FieldAppVersion holds the string denoting the app_version field in the database.
	FieldAppVersion = "app_version"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// UserFieldID holds the string denoting the ID field of the User.
	UserFieldID = "id"
	// Table holds the table name of the userdevice in the database.
	Table = "user_devices"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_devices"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for userdevice fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldApnsToken,
	FieldBundleID,
	FieldEnvironment,
	FieldAppVersion,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "user_devices"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_id",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/foodsea/core/ent/runtime"
var (
	Hooks [1]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// ApnsTokenValidator is a validator for the "apns_token" field. It is called by the builders before save.
	ApnsTokenValidator func(string) error
	// BundleIDValidator is a validator for the "bundle_id" field. It is called by the builders before save.
	BundleIDValidator func(string) error
)

// Environment defines the type for the "environment" enum field.
type Environment string

// Environment values.
const (
	EnvironmentSandbox    Environment = "sandbox"
	EnvironmentProduction Environment = "production"
)

func (e Environment) String() string {
	return string(e)
}

// EnvironmentValidator is a validator for the "environment" field enum values. It is called by the builders before save.
func EnvironmentValidator(e Environment) error {
	switch e {
	case EnvironmentSandbox, EnvironmentProduction:
		return nil
	default:
		return fmt.Errorf("userdevice: invalid enum value for environment field: %q", e)
	}
}

// OrderOption defines the ordering options for the UserDevice queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByApnsToken orders the results by the apns_token field.
func ByApnsToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApnsToken, opts...).ToFunc()
}

// ByBundleID orders the results by the bundle_id field.
func ByBundleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBundleID, opts...).ToFunc()
}

// ByEnvironment orders the results by the environment field.
func ByEnvironment(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnvironment, opts...).ToFunc()
}

// ByAppVersion orders the results by the app_version field.
func ByAppVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppVersion, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, UserFieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
