// Code generated by ent, DO NOT EDIT.

package userdevice

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/foodsea/core/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEQ(FieldUpdatedAt, v))
}

// ApnsToken applies equality check predicate on the "apns_token" field. It's identical to ApnsTokenEQ.
func ApnsToken(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEQ(FieldApnsToken, v))
}

// BundleID applies equality check predicate on the "bundle_id" field. It's identical to BundleIDEQ.
func BundleID(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEQ(FieldBundleID, v))
}

// AppVersion applies equality check predicate on the "app_version" field. It's identical to AppVersionEQ.
func AppVersion(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEQ(FieldAppVersion, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldLTE(FieldUpdatedAt, v))
}

// ApnsTokenEQ applies the EQ predicate on the "apns_token" field.
func ApnsTokenEQ(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEQ(FieldApnsToken, v))
}

// ApnsTokenNEQ applies the NEQ predicate on the "apns_token" field.
func ApnsTokenNEQ(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNEQ(FieldApnsToken, v))
}

// ApnsTokenIn applies the In predicate on the "apns_token" field.
func ApnsTokenIn(vs ...string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldIn(FieldApnsToken, vs...))
}

// ApnsTokenNotIn applies the NotIn predicate on the "apns_token" field.
func ApnsTokenNotIn(vs ...string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNotIn(FieldApnsToken, vs...))
}

// ApnsTokenGT applies the GT predicate on the "apns_token" field.
func ApnsTokenGT(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldGT(FieldApnsToken, v))
}

// ApnsTokenGTE applies the GTE predicate on the "apns_token" field.
func ApnsTokenGTE(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldGTE(FieldApnsToken, v))
}

// ApnsTokenLT applies the LT predicate on the "apns_token" field.
func ApnsTokenLT(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldLT(FieldApnsToken, v))
}

// ApnsTokenLTE applies the LTE predicate on the "apns_token" field.
func ApnsTokenLTE(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldLTE(FieldApnsToken, v))
}

// ApnsTokenContains applies the Contains predicate on the "apns_token" field.
func ApnsTokenContains(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldContains(FieldApnsToken, v))
}

// ApnsTokenHasPrefix applies the HasPrefix predicate on the "apns_token" field.
func ApnsTokenHasPrefix(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldHasPrefix(FieldApnsToken, v))
}

// ApnsTokenHasSuffix applies the HasSuffix predicate on the "apns_token" field.
func ApnsTokenHasSuffix(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldHasSuffix(FieldApnsToken, v))
}

// ApnsTokenEqualFold applies the EqualFold predicate on the "apns_token" field.
func ApnsTokenEqualFold(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEqualFold(FieldApnsToken, v))
}

// ApnsTokenContainsFold applies the ContainsFold predicate on the "apns_token" field.
func ApnsTokenContainsFold(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldContainsFold(FieldApnsToken, v))
}

// BundleIDEQ applies the EQ predicate on the "bundle_id" field.
func BundleIDEQ(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEQ(FieldBundleID, v))
}

// BundleIDNEQ applies the NEQ predicate on the "bundle_id" field.
func BundleIDNEQ(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNEQ(FieldBundleID, v))
}

// BundleIDIn applies the In predicate on the "bundle_id" field.
func BundleIDIn(vs ...string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldIn(FieldBundleID, vs...))
}

// BundleIDNotIn applies the NotIn predicate on the "bundle_id" field.
func BundleIDNotIn(vs ...string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNotIn(FieldBundleID, vs...))
}

// BundleIDGT applies the GT predicate on the "bundle_id" field.
func BundleIDGT(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldGT(FieldBundleID, v))
}

// BundleIDGTE applies the GTE predicate on the "bundle_id" field.
func BundleIDGTE(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldGTE(FieldBundleID, v))
}

// BundleIDLT applies the LT predicate on the "bundle_id" field.
func BundleIDLT(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldLT(FieldBundleID, v))
}

// BundleIDLTE applies the LTE predicate on the "bundle_id" field.
func BundleIDLTE(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldLTE(FieldBundleID, v))
}

// BundleIDContains applies the Contains predicate on the "bundle_id" field.
func BundleIDContains(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldContains(FieldBundleID, v))
}

// BundleIDHasPrefix applies the HasPrefix predicate on the "bundle_id" field.
func BundleIDHasPrefix(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldHasPrefix(FieldBundleID, v))
}

// BundleIDHasSuffix applies the HasSuffix predicate on the "bundle_id" field.
func BundleIDHasSuffix(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldHasSuffix(FieldBundleID, v))
}

// BundleIDEqualFold applies the EqualFold predicate on the "bundle_id" field.
func BundleIDEqualFold(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEqualFold(FieldBundleID, v))
}

// BundleIDContainsFold applies the ContainsFold predicate on the "bundle_id" field.
func BundleIDContainsFold(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldContainsFold(FieldBundleID, v))
}

// EnvironmentEQ applies the EQ predicate on the "environment" field.
func EnvironmentEQ(v Environment) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEQ(FieldEnvironment, v))
}

// EnvironmentNEQ applies the NEQ predicate on the "environment" field.
func EnvironmentNEQ(v Environment) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNEQ(FieldEnvironment, v))
}

// EnvironmentIn applies the In predicate on the "environment" field.
func EnvironmentIn(vs ...Environment) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldIn(FieldEnvironment, vs...))
}

// EnvironmentNotIn applies the NotIn predicate on the "environment" field.
func EnvironmentNotIn(vs ...Environment) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNotIn(FieldEnvironment, vs...))
}

// AppVersionEQ applies the EQ predicate on the "app_version" field.
func AppVersionEQ(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEQ(FieldAppVersion, v))
}

// AppVersionNEQ applies the NEQ predicate on the "app_version" field.
func AppVersionNEQ(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNEQ(FieldAppVersion, v))
}

// AppVersionIn applies the In predicate on the "app_version" field.
func AppVersionIn(vs ...string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldIn(FieldAppVersion, vs...))
}

// AppVersionNotIn applies the NotIn predicate on the "app_version" field.
func AppVersionNotIn(vs ...string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNotIn(FieldAppVersion, vs...))
}

// AppVersionGT applies the GT predicate on the "app_version" field.
func AppVersionGT(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldGT(FieldAppVersion, v))
}

// AppVersionGTE applies the GTE predicate on the "app_version" field.
func AppVersionGTE(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldGTE(FieldAppVersion, v))
}

// AppVersionLT applies the LT predicate on the "app_version" field.
func AppVersionLT(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldLT(FieldAppVersion, v))
}

// AppVersionLTE applies the LTE predicate on the "app_version" field.
func AppVersionLTE(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldLTE(FieldAppVersion, v))
}

// AppVersionContains applies the Contains predicate on the "app_version" field.
func AppVersionContains(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldContains(FieldAppVersion, v))
}

// AppVersionHasPrefix applies the HasPrefix predicate on the "app_version" field.
func AppVersionHasPrefix(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldHasPrefix(FieldAppVersion, v))
}

// AppVersionHasSuffix applies the HasSuffix predicate on the "app_version" field.
func AppVersionHasSuffix(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldHasSuffix(FieldAppVersion, v))
}

// AppVersionIsNil applies the IsNil predicate on the "app_version" field.
func AppVersionIsNil() predicate.UserDevice {
	return predicate.UserDevice(sql.FieldIsNull(FieldAppVersion))
}

// AppVersionNotNil applies the NotNil predicate on the "app_version" field.
func AppVersionNotNil() predicate.UserDevice {
	return predicate.UserDevice(sql.FieldNotNull(FieldAppVersion))
}

// AppVersionEqualFold applies the EqualFold predicate on the "app_version" field.
func AppVersionEqualFold(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldEqualFold(FieldAppVersion, v))
}

// AppVersionContainsFold applies the ContainsFold predicate on the "app_version" field.
func AppVersionContainsFold(v string) predicate.UserDevice {
	return predicate.UserDevice(sql.FieldContainsFold(FieldAppVersion, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserDevice {
	return predicate.UserDevice(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserDevice {
	return predicate.UserDevice(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserDevice) predicate.UserDevice {
	return predicate.UserDevice(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserDevice) predicate.UserDevice {
	return predicate.UserDevice(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserDevice) predicate.UserDevice {
	return predicate.UserDevice(sql.NotPredicates(p))
}
