// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: optimization/optimization.proto

package optimization

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OptimizationService_RunOptimization_FullMethodName = "/optimization.OptimizationService/RunOptimization"
	OptimizationService_GetResult_FullMethodName       = "/optimization.OptimizationService/GetResult"
	OptimizationService_LockResult_FullMethodName      = "/optimization.OptimizationService/LockResult"
	OptimizationService_UnlockResult_FullMethodName    = "/optimization.OptimizationService/UnlockResult"
)

// OptimizationServiceClient is the client API for OptimizationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OptimizationServiceClient interface {
	RunOptimization(ctx context.Context, in *RunOptimizationRequest, opts ...grpc.CallOption) (*RunOptimizationResponse, error)
	GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error)
	LockResult(ctx context.Context, in *LockResultRequest, opts ...grpc.CallOption) (*LockResultResponse, error)
	UnlockResult(ctx context.Context, in *UnlockResultRequest, opts ...grpc.CallOption) (*UnlockResultResponse, error)
}

type optimizationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOptimizationServiceClient(cc grpc.ClientConnInterface) OptimizationServiceClient {
	return &optimizationServiceClient{cc}
}

func (c *optimizationServiceClient) RunOptimization(ctx context.Context, in *RunOptimizationRequest, opts ...grpc.CallOption) (*RunOptimizationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunOptimizationResponse)
	err := c.cc.Invoke(ctx, OptimizationService_RunOptimization_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizationServiceClient) GetResult(ctx context.Context, in *GetResultRequest, opts ...grpc.CallOption) (*GetResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResultResponse)
	err := c.cc.Invoke(ctx, OptimizationService_GetResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizationServiceClient) LockResult(ctx context.Context, in *LockResultRequest, opts ...grpc.CallOption) (*LockResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockResultResponse)
	err := c.cc.Invoke(ctx, OptimizationService_LockResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *optimizationServiceClient) UnlockResult(ctx context.Context, in *UnlockResultRequest, opts ...grpc.CallOption) (*UnlockResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockResultResponse)
	err := c.cc.Invoke(ctx, OptimizationService_UnlockResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptimizationServiceServer is the server API for OptimizationService service.
// All implementations must embed UnimplementedOptimizationServiceServer
// for forward compatibility.
type OptimizationServiceServer interface {
	RunOptimization(context.Context, *RunOptimizationRequest) (*RunOptimizationResponse, error)
	GetResult(context.Context, *GetResultRequest) (*GetResultResponse, error)
	LockResult(context.Context, *LockResultRequest) (*LockResultResponse, error)
	UnlockResult(context.Context, *UnlockResultRequest) (*UnlockResultResponse, error)
	mustEmbedUnimplementedOptimizationServiceServer()
}

// UnimplementedOptimizationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOptimizationServiceServer struct{}

func (UnimplementedOptimizationServiceServer) RunOptimization(context.Context, *RunOptimizationRequest) (*RunOptimizationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunOptimization not implemented")
}
func (UnimplementedOptimizationServiceServer) GetResult(context.Context, *GetResultRequest) (*GetResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetResult not implemented")
}
func (UnimplementedOptimizationServiceServer) LockResult(context.Context, *LockResultRequest) (*LockResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LockResult not implemented")
}
func (UnimplementedOptimizationServiceServer) UnlockResult(context.Context, *UnlockResultRequest) (*UnlockResultResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlockResult not implemented")
}
func (UnimplementedOptimizationServiceServer) mustEmbedUnimplementedOptimizationServiceServer() {}
func (UnimplementedOptimizationServiceServer) testEmbeddedByValue()                             {}

// UnsafeOptimizationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OptimizationServiceServer will
// result in compilation errors.
type UnsafeOptimizationServiceServer interface {
	mustEmbedUnimplementedOptimizationServiceServer()
}

func RegisterOptimizationServiceServer(s grpc.ServiceRegistrar, srv OptimizationServiceServer) {
	// If the following call panics, it indicates UnimplementedOptimizationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OptimizationService_ServiceDesc, srv)
}

func _OptimizationService_RunOptimization_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunOptimizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizationServiceServer).RunOptimization(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizationService_RunOptimization_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizationServiceServer).RunOptimization(ctx, req.(*RunOptimizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizationService_GetResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizationServiceServer).GetResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizationService_GetResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizationServiceServer).GetResult(ctx, req.(*GetResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizationService_LockResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizationServiceServer).LockResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizationService_LockResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizationServiceServer).LockResult(ctx, req.(*LockResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OptimizationService_UnlockResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimizationServiceServer).UnlockResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OptimizationService_UnlockResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimizationServiceServer).UnlockResult(ctx, req.(*UnlockResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OptimizationService_ServiceDesc is the grpc.ServiceDesc for OptimizationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OptimizationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "optimization.OptimizationService",
	HandlerType: (*OptimizationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunOptimization",
			Handler:    _OptimizationService_RunOptimization_Handler,
		},
		{
			MethodName: "GetResult",
			Handler:    _OptimizationService_GetResult_Handler,
		},
		{
			MethodName: "LockResult",
			Handler:    _OptimizationService_LockResult_Handler,
		},
		{
			MethodName: "UnlockResult",
			Handler:    _OptimizationService_UnlockResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optimization/optimization.proto",
}
