apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config
  namespace: foodsea
data:
  ENV: production
  SERVER_PORT: "8081"
  GRPC_PORT: "9091"
  DB_HOST: core-postgres
  DB_PORT: "5432"
  DB_NAME: core_db
  REDIS_URL: redis://redis:6379/0
  KAFKA_BROKERS: kafka:9092
  JWT_ACCESS_TTL: 15m
  JWT_REFRESH_TTL: 720h
