apiVersion: v1
kind: Secret
metadata:
  name: core-secrets
  namespace: foodsea
type: Opaque
stringData:
  DB_URL: postgres://postgres:REPLACE_ME@core-postgres:5432/core_db?sslmode=require
  DB_USER: postgres
  DB_PASSWORD: REPLACE_ME
  JWT_SECRET: REPLACE_ME
