apiVersion: v1
kind: Secret
metadata:
  name: core-secrets
  namespace: foodsea
type: Opaque
stringData:
  DB_URL: postgres://postgres:changeme@core-postgres:5432/core_db?sslmode=require
  DB_USER: postgres
  DB_PASSWORD: changeme
  JWT_SECRET: change-me-in-production
