apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: foodsea
spec:
  selector:
    app: core-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  - name: grpc
    port: 9091
    targetPort: 9091
  type: ClusterIP
