// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OptimizationItemsColumns holds the columns for the "optimization_items" table.
	OptimizationItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "price_kopecks", Type: field.TypeInt64},
		{Name: "product_name", Type: field.TypeString},
		{Name: "store_name", Type: field.TypeString},
		{Name: "quantity", Type: field.TypeInt16},
		{Name: "product_id", Type: field.TypeUUID},
		{Name: "store_id", Type: field.TypeUUID},
		{Name: "result_id", Type: field.TypeUUID},
	}
	// OptimizationItemsTable holds the schema information for the "optimization_items" table.
	OptimizationItemsTable = &schema.Table{
		Name:       "optimization_items",
		Columns:    OptimizationItemsColumns,
		PrimaryKey: []*schema.Column{OptimizationItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "optimization_items_optimization_results_items",
				Columns:    []*schema.Column{OptimizationItemsColumns[7]},
				RefColumns: []*schema.Column{OptimizationResultsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "optimizationitem_result_id",
				Unique:  false,
				Columns: []*schema.Column{OptimizationItemsColumns[7]},
			},
		},
	}
	// OptimizationResultsColumns holds the columns for the "optimization_results" table.
	OptimizationResultsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "total_kopecks", Type: field.TypeInt64},
		{Name: "delivery_kopecks", Type: field.TypeInt64, Default: 0},
		{Name: "savings_kopecks", Type: field.TypeInt64, Default: 0},
		{Name: "cart_hash", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "is_approximate", Type: field.TypeBool, Default: false},
	}
	// OptimizationResultsTable holds the schema information for the "optimization_results" table.
	OptimizationResultsTable = &schema.Table{
		Name:       "optimization_results",
		Columns:    OptimizationResultsColumns,
		PrimaryKey: []*schema.Column{OptimizationResultsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "optimizationresult_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{OptimizationResultsColumns[8], OptimizationResultsColumns[1]},
				Annotation: &entsql.IndexAnnotation{
					DescColumns: map[string]bool{
						OptimizationResultsColumns[1].Name: true,
					},
				},
			},
			{
				Name:    "optimizationresult_cart_hash",
				Unique:  false,
				Columns: []*schema.Column{OptimizationResultsColumns[6]},
			},
			{
				Name:    "optimizationresult_status",
				Unique:  false,
				Columns: []*schema.Column{OptimizationResultsColumns[7]},
			},
		},
	}
	// SubstitutionsColumns holds the columns for the "substitutions" table.
	SubstitutionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "total_saving_kopecks", Type: field.TypeInt64},
		{Name: "price_delta_kopecks", Type: field.TypeInt64},
		{Name: "delivery_delta_kopecks", Type: field.TypeInt64},
		{Name: "old_price_kopecks", Type: field.TypeInt64},
		{Name: "new_price_kopecks", Type: field.TypeInt64},
		{Name: "analog_product_name", Type: field.TypeString},
		{Name: "new_store_name", Type: field.TypeString},
		{Name: "original_product_name", Type: field.TypeString},
		{Name: "score", Type: field.TypeFloat64, SchemaType: map[string]string{"postgres": "decimal(5,4)"}},
		{Name: "original_store_id", Type: field.TypeUUID},
		{Name: "original_product_id", Type: field.TypeUUID},
		{Name: "analog_product_id", Type: field.TypeUUID},
		{Name: "new_store_id", Type: field.TypeUUID},
		{Name: "is_cross_store", Type: field.TypeBool},
		{Name: "result_id", Type: field.TypeUUID},
	}
	// SubstitutionsTable holds the schema information for the "substitutions" table.
	SubstitutionsTable = &schema.Table{
		Name:       "substitutions",
		Columns:    SubstitutionsColumns,
		PrimaryKey: []*schema.Column{SubstitutionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "substitutions_optimization_results_substitutions",
				Columns:    []*schema.Column{SubstitutionsColumns[15]},
				RefColumns: []*schema.Column{OptimizationResultsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "substitution_result_id",
				Unique:  false,
				Columns: []*schema.Column{SubstitutionsColumns[15]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OptimizationItemsTable,
		OptimizationResultsTable,
		SubstitutionsTable,
	}
)

func init() {
	OptimizationItemsTable.ForeignKeys[0].RefTable = OptimizationResultsTable
	OptimizationResultsTable.Annotation = &entsql.Annotation{}
	OptimizationResultsTable.Annotation.Checks = map[string]string{
		"optimization_result_status_check": "status IN ('active', 'locked', 'expired')",
	}
	SubstitutionsTable.ForeignKeys[0].RefTable = OptimizationResultsTable
}
