apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: foodsea-prod

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: patch-config.yaml
  - target:
      kind: Ingress
      name: foodsea-api
    path: patch-ingress-host.yaml
  - target:
      kind: Ingress
      name: foodsea-minio-public
    path: patch-ingress-host.yaml
