apiVersion: v1
kind: ConfigMap
metadata:
  name: core-config
data:
  ENV: production
  S3_PUBLIC_BASE_URL: http://api.foodsea.example.com/product-images
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: optimization-config
data:
  ENV: production
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ordering-config
data:
  ENV: production
