// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/foodsea/optimization/ent/optimizationitem"
	"github.com/foodsea/optimization/ent/optimizationresult"
	"github.com/foodsea/optimization/ent/predicate"
	"github.com/foodsea/optimization/ent/substitution"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 3)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   optimizationitem.Table,
			Columns: optimizationitem.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: optimizationitem.FieldID,
			},
		},
		Type: "OptimizationItem",
		Fields: map[string]*sqlgraph.FieldSpec{
			optimizationitem.FieldPriceKopecks: {Type: field.TypeInt64, Column: optimizationitem.FieldPriceKopecks},
			optimizationitem.FieldProductName:  {Type: field.TypeString, Column: optimizationitem.FieldProductName},
			optimizationitem.FieldStoreName:    {Type: field.TypeString, Column: optimizationitem.FieldStoreName},
			optimizationitem.FieldQuantity:     {Type: field.TypeInt16, Column: optimizationitem.FieldQuantity},
			optimizationitem.FieldProductID:    {Type: field.TypeUUID, Column: optimizationitem.FieldProductID},
			optimizationitem.FieldStoreID:      {Type: field.TypeUUID, Column: optimizationitem.FieldStoreID},
			optimizationitem.FieldResultID:     {Type: field.TypeUUID, Column: optimizationitem.FieldResultID},
		},
	}
	graph.Nodes[1] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   optimizationresult.Table,
			Columns: optimizationresult.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: optimizationresult.FieldID,
			},
		},
		Type: "OptimizationResult",
		Fields: map[string]*sqlgraph.FieldSpec{
			optimizationresult.FieldCreatedAt:       {Type: field.TypeTime, Column: optimizationresult.FieldCreatedAt},
			optimizationresult.FieldUpdatedAt:       {Type: field.TypeTime, Column: optimizationresult.FieldUpdatedAt},
			optimizationresult.FieldTotalKopecks:    {Type: field.TypeInt64, Column: optimizationresult.FieldTotalKopecks},
			optimizationresult.FieldDeliveryKopecks: {Type: field.TypeInt64, Column: optimizationresult.FieldDeliveryKopecks},
			optimizationresult.FieldSavingsKopecks:  {Type: field.TypeInt64, Column: optimizationresult.FieldSavingsKopecks},
			optimizationresult.FieldCartHash:        {Type: field.TypeString, Column: optimizationresult.FieldCartHash},
			optimizationresult.FieldStatus:          {Type: field.TypeString, Column: optimizationresult.FieldStatus},
			optimizationresult.FieldUserID:          {Type: field.TypeUUID, Column: optimizationresult.FieldUserID},
			optimizationresult.FieldIsApproximate:   {Type: field.TypeBool, Column: optimizationresult.FieldIsApproximate},
		},
	}
	graph.Nodes[2] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   substitution.Table,
			Columns: substitution.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: substitution.FieldID,
			},
		},
		Type: "Substitution",
		Fields: map[string]*sqlgraph.FieldSpec{
			substitution.FieldTotalSavingKopecks:   {Type: field.TypeInt64, Column: substitution.FieldTotalSavingKopecks},
			substitution.FieldPriceDeltaKopecks:    {Type: field.TypeInt64, Column: substitution.FieldPriceDeltaKopecks},
			substitution.FieldDeliveryDeltaKopecks: {Type: field.TypeInt64, Column: substitution.FieldDeliveryDeltaKopecks},
			substitution.FieldOldPriceKopecks:      {Type: field.TypeInt64, Column: substitution.FieldOldPriceKopecks},
			substitution.FieldNewPriceKopecks:      {Type: field.TypeInt64, Column: substitution.FieldNewPriceKopecks},
			substitution.FieldAnalogProductName:    {Type: field.TypeString, Column: substitution.FieldAnalogProductName},
			substitution.FieldNewStoreName:         {Type: field.TypeString, Column: substitution.FieldNewStoreName},
			substitution.FieldOriginalProductName:  {Type: field.TypeString, Column: substitution.FieldOriginalProductName},
			substitution.FieldScore:                {Type: field.TypeFloat64, Column: substitution.FieldScore},
			substitution.FieldOriginalStoreID:      {Type: field.TypeUUID, Column: substitution.FieldOriginalStoreID},
			substitution.FieldOriginalProductID:    {Type: field.TypeUUID, Column: substitution.FieldOriginalProductID},
			substitution.FieldAnalogProductID:      {Type: field.TypeUUID, Column: substitution.FieldAnalogProductID},
			substitution.FieldNewStoreID:           {Type: field.TypeUUID, Column: substitution.FieldNewStoreID},
			substitution.FieldIsCrossStore:         {Type: field.TypeBool, Column: substitution.FieldIsCrossStore},
			substitution.FieldResultID:             {Type: field.TypeUUID, Column: substitution.FieldResultID},
		},
	}
	graph.MustAddE(
		"result",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   optimizationitem.ResultTable,
			Columns: []string{optimizationitem.ResultColumn},
			Bidi:    false,
		},
		"OptimizationItem",
		"OptimizationResult",
	)
	graph.MustAddE(
		"items",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   optimizationresult.ItemsTable,
			Columns: []string{optimizationresult.ItemsColumn},
			Bidi:    false,
		},
		"OptimizationResult",
		"OptimizationItem",
	)
	graph.MustAddE(
		"substitutions",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   optimizationresult.SubstitutionsTable,
			Columns: []string{optimizationresult.SubstitutionsColumn},
			Bidi:    false,
		},
		"OptimizationResult",
		"Substitution",
	)
	graph.MustAddE(
		"result",
		&sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   substitution.ResultTable,
			Columns: []string{substitution.ResultColumn},
			Bidi:    false,
		},
		"Substitution",
		"OptimizationResult",
	)
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (_q *OptimizationItemQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the OptimizationItemQuery builder.
func (_q *OptimizationItemQuery) Filter() *OptimizationItemFilter {
	return &OptimizationItemFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *OptimizationItemMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the OptimizationItemMutation builder.
func (m *OptimizationItemMutation) Filter() *OptimizationItemFilter {
	return &OptimizationItemFilter{config: m.config, predicateAdder: m}
}

// OptimizationItemFilter provides a generic filtering capability at runtime for OptimizationItemQuery.
type OptimizationItemFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *OptimizationItemFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *OptimizationItemFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(optimizationitem.FieldID))
}

// WherePriceKopecks applies the entql int64 predicate on the price_kopecks field.
func (f *OptimizationItemFilter) WherePriceKopecks(p entql.Int64P) {
	f.Where(p.Field(optimizationitem.FieldPriceKopecks))
}

// WhereProductName applies the entql string predicate on the product_name field.
func (f *OptimizationItemFilter) WhereProductName(p entql.StringP) {
	f.Where(p.Field(optimizationitem.FieldProductName))
}

// WhereStoreName applies the entql string predicate on the store_name field.
func (f *OptimizationItemFilter) WhereStoreName(p entql.StringP) {
	f.Where(p.Field(optimizationitem.FieldStoreName))
}

// WhereQuantity applies the entql int16 predicate on the quantity field.
func (f *OptimizationItemFilter) WhereQuantity(p entql.Int16P) {
	f.Where(p.Field(optimizationitem.FieldQuantity))
}

// WhereProductID applies the entql [16]byte predicate on the product_id field.
func (f *OptimizationItemFilter) WhereProductID(p entql.ValueP) {
	f.Where(p.Field(optimizationitem.FieldProductID))
}

// WhereStoreID applies the entql [16]byte predicate on the store_id field.
func (f *OptimizationItemFilter) WhereStoreID(p entql.ValueP) {
	f.Where(p.Field(optimizationitem.FieldStoreID))
}

// WhereResultID applies the entql [16]byte predicate on the result_id field.
func (f *OptimizationItemFilter) WhereResultID(p entql.ValueP) {
	f.Where(p.Field(optimizationitem.FieldResultID))
}

// WhereHasResult applies a predicate to check if query has an edge result.
func (f *OptimizationItemFilter) WhereHasResult() {
	f.Where(entql.HasEdge("result"))
}

// WhereHasResultWith applies a predicate to check if query has an edge result with a given conditions (other predicates).
func (f *OptimizationItemFilter) WhereHasResultWith(preds ...predicate.OptimizationResult) {
	f.Where(entql.HasEdgeWith("result", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *OptimizationResultQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the OptimizationResultQuery builder.
func (_q *OptimizationResultQuery) Filter() *OptimizationResultFilter {
	return &OptimizationResultFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *OptimizationResultMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the OptimizationResultMutation builder.
func (m *OptimizationResultMutation) Filter() *OptimizationResultFilter {
	return &OptimizationResultFilter{config: m.config, predicateAdder: m}
}

// OptimizationResultFilter provides a generic filtering capability at runtime for OptimizationResultQuery.
type OptimizationResultFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *OptimizationResultFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[1].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *OptimizationResultFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(optimizationresult.FieldID))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *OptimizationResultFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(optimizationresult.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *OptimizationResultFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(optimizationresult.FieldUpdatedAt))
}

// WhereTotalKopecks applies the entql int64 predicate on the total_kopecks field.
func (f *OptimizationResultFilter) WhereTotalKopecks(p entql.Int64P) {
	f.Where(p.Field(optimizationresult.FieldTotalKopecks))
}

// WhereDeliveryKopecks applies the entql int64 predicate on the delivery_kopecks field.
func (f *OptimizationResultFilter) WhereDeliveryKopecks(p entql.Int64P) {
	f.Where(p.Field(optimizationresult.FieldDeliveryKopecks))
}

// WhereSavingsKopecks applies the entql int64 predicate on the savings_kopecks field.
func (f *OptimizationResultFilter) WhereSavingsKopecks(p entql.Int64P) {
	f.Where(p.Field(optimizationresult.FieldSavingsKopecks))
}

// WhereCartHash applies the entql string predicate on the cart_hash field.
func (f *OptimizationResultFilter) WhereCartHash(p entql.StringP) {
	f.Where(p.Field(optimizationresult.FieldCartHash))
}

// WhereStatus applies the entql string predicate on the status field.
func (f *OptimizationResultFilter) WhereStatus(p entql.StringP) {
	f.Where(p.Field(optimizationresult.FieldStatus))
}

// WhereUserID applies the entql [16]byte predicate on the user_id field.
func (f *OptimizationResultFilter) WhereUserID(p entql.ValueP) {
	f.Where(p.Field(optimizationresult.FieldUserID))
}

// WhereIsApproximate applies the entql bool predicate on the is_approximate field.
func (f *OptimizationResultFilter) WhereIsApproximate(p entql.BoolP) {
	f.Where(p.Field(optimizationresult.FieldIsApproximate))
}

// WhereHasItems applies a predicate to check if query has an edge items.
func (f *OptimizationResultFilter) WhereHasItems() {
	f.Where(entql.HasEdge("items"))
}

// WhereHasItemsWith applies a predicate to check if query has an edge items with a given conditions (other predicates).
func (f *OptimizationResultFilter) WhereHasItemsWith(preds ...predicate.OptimizationItem) {
	f.Where(entql.HasEdgeWith("items", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// WhereHasSubstitutions applies a predicate to check if query has an edge substitutions.
func (f *OptimizationResultFilter) WhereHasSubstitutions() {
	f.Where(entql.HasEdge("substitutions"))
}

// WhereHasSubstitutionsWith applies a predicate to check if query has an edge substitutions with a given conditions (other predicates).
func (f *OptimizationResultFilter) WhereHasSubstitutionsWith(preds ...predicate.Substitution) {
	f.Where(entql.HasEdgeWith("substitutions", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}

// addPredicate implements the predicateAdder interface.
func (_q *SubstitutionQuery) addPredicate(pred func(s *sql.Selector)) {
	_q.predicates = append(_q.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the SubstitutionQuery builder.
func (_q *SubstitutionQuery) Filter() *SubstitutionFilter {
	return &SubstitutionFilter{config: _q.config, predicateAdder: _q}
}

// addPredicate implements the predicateAdder interface.
func (m *SubstitutionMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the SubstitutionMutation builder.
func (m *SubstitutionMutation) Filter() *SubstitutionFilter {
	return &SubstitutionFilter{config: m.config, predicateAdder: m}
}

// SubstitutionFilter provides a generic filtering capability at runtime for SubstitutionQuery.
type SubstitutionFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *SubstitutionFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[2].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql [16]byte predicate on the id field.
func (f *SubstitutionFilter) WhereID(p entql.ValueP) {
	f.Where(p.Field(substitution.FieldID))
}

// WhereTotalSavingKopecks applies the entql int64 predicate on the total_saving_kopecks field.
func (f *SubstitutionFilter) WhereTotalSavingKopecks(p entql.Int64P) {
	f.Where(p.Field(substitution.FieldTotalSavingKopecks))
}

// WherePriceDeltaKopecks applies the entql int64 predicate on the price_delta_kopecks field.
func (f *SubstitutionFilter) WherePriceDeltaKopecks(p entql.Int64P) {
	f.Where(p.Field(substitution.FieldPriceDeltaKopecks))
}

// WhereDeliveryDeltaKopecks applies the entql int64 predicate on the delivery_delta_kopecks field.
func (f *SubstitutionFilter) WhereDeliveryDeltaKopecks(p entql.Int64P) {
	f.Where(p.Field(substitution.FieldDeliveryDeltaKopecks))
}

// WhereOldPriceKopecks applies the entql int64 predicate on the old_price_kopecks field.
func (f *SubstitutionFilter) WhereOldPriceKopecks(p entql.Int64P) {
	f.Where(p.Field(substitution.FieldOldPriceKopecks))
}

// WhereNewPriceKopecks applies the entql int64 predicate on the new_price_kopecks field.
func (f *SubstitutionFilter) WhereNewPriceKopecks(p entql.Int64P) {
	f.Where(p.Field(substitution.FieldNewPriceKopecks))
}

// WhereAnalogProductName applies the entql string predicate on the analog_product_name field.
func (f *SubstitutionFilter) WhereAnalogProductName(p entql.StringP) {
	f.Where(p.Field(substitution.FieldAnalogProductName))
}

// WhereNewStoreName applies the entql string predicate on the new_store_name field.
func (f *SubstitutionFilter) WhereNewStoreName(p entql.StringP) {
	f.Where(p.Field(substitution.FieldNewStoreName))
}

// WhereOriginalProductName applies the entql string predicate on the original_product_name field.
func (f *SubstitutionFilter) WhereOriginalProductName(p entql.StringP) {
	f.Where(p.Field(substitution.FieldOriginalProductName))
}

// WhereScore applies the entql float64 predicate on the score field.
func (f *SubstitutionFilter) WhereScore(p entql.Float64P) {
	f.Where(p.Field(substitution.FieldScore))
}

// WhereOriginalStoreID applies the entql [16]byte predicate on the original_store_id field.
func (f *SubstitutionFilter) WhereOriginalStoreID(p entql.ValueP) {
	f.Where(p.Field(substitution.FieldOriginalStoreID))
}

// WhereOriginalProductID applies the entql [16]byte predicate on the original_product_id field.
func (f *SubstitutionFilter) WhereOriginalProductID(p entql.ValueP) {
	f.Where(p.Field(substitution.FieldOriginalProductID))
}

// WhereAnalogProductID applies the entql [16]byte predicate on the analog_product_id field.
func (f *SubstitutionFilter) WhereAnalogProductID(p entql.ValueP) {
	f.Where(p.Field(substitution.FieldAnalogProductID))
}

// WhereNewStoreID applies the entql [16]byte predicate on the new_store_id field.
func (f *SubstitutionFilter) WhereNewStoreID(p entql.ValueP) {
	f.Where(p.Field(substitution.FieldNewStoreID))
}

// WhereIsCrossStore applies the entql bool predicate on the is_cross_store field.
func (f *SubstitutionFilter) WhereIsCrossStore(p entql.BoolP) {
	f.Where(p.Field(substitution.FieldIsCrossStore))
}

// WhereResultID applies the entql [16]byte predicate on the result_id field.
func (f *SubstitutionFilter) WhereResultID(p entql.ValueP) {
	f.Where(p.Field(substitution.FieldResultID))
}

// WhereHasResult applies a predicate to check if query has an edge result.
func (f *SubstitutionFilter) WhereHasResult() {
	f.Where(entql.HasEdge("result"))
}

// WhereHasResultWith applies a predicate to check if query has an edge result with a given conditions (other predicates).
func (f *SubstitutionFilter) WhereHasResultWith(preds ...predicate.OptimizationResult) {
	f.Where(entql.HasEdgeWith("result", sqlgraph.WrapFunc(func(s *sql.Selector) {
		for _, p := range preds {
			p(s)
		}
	})))
}
