// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/foodsea/optimization/ent/optimizationitem"
	"github.com/foodsea/optimization/ent/optimizationresult"
	"github.com/foodsea/optimization/ent/predicate"
	"github.com/google/uuid"
)

// OptimizationItemUpdate is the builder for updating OptimizationItem entities.
type OptimizationItemUpdate struct {
	config
	hooks    []Hook
	mutation *OptimizationItemMutation
}

// Where appends a list predicates to the OptimizationItemUpdate builder.
func (_u *OptimizationItemUpdate) Where(ps ...predicate.OptimizationItem) *OptimizationItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPriceKopecks sets the "price_kopecks" field.
func (_u *OptimizationItemUpdate) SetPriceKopecks(v int64) *OptimizationItemUpdate {
	_u.mutation.ResetPriceKopecks()
	_u.mutation.SetPriceKopecks(v)
	return _u
}

// SetNillablePriceKopecks sets the "price_kopecks" field if the given value is not nil.
func (_u *OptimizationItemUpdate) SetNillablePriceKopecks(v *int64) *OptimizationItemUpdate {
	if v != nil {
		_u.SetPriceKopecks(*v)
	}
	return _u
}

// AddPriceKopecks adds value to the "price_kopecks" field.
func (_u *OptimizationItemUpdate) AddPriceKopecks(v int64) *OptimizationItemUpdate {
	_u.mutation.AddPriceKopecks(v)
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *OptimizationItemUpdate) SetProductName(v string) *OptimizationItemUpdate {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *OptimizationItemUpdate) SetNillableProductName(v *string) *OptimizationItemUpdate {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetStoreName sets the "store_name" field.
func (_u *OptimizationItemUpdate) SetStoreName(v string) *OptimizationItemUpdate {
	_u.mutation.SetStoreName(v)
	return _u
}

// SetNillableStoreName sets the "store_name" field if the given value is not nil.
func (_u *OptimizationItemUpdate) SetNillableStoreName(v *string) *OptimizationItemUpdate {
	if v != nil {
		_u.SetStoreName(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OptimizationItemUpdate) SetQuantity(v int16) *OptimizationItemUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OptimizationItemUpdate) SetNillableQuantity(v *int16) *OptimizationItemUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OptimizationItemUpdate) AddQuantity(v int16) *OptimizationItemUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *OptimizationItemUpdate) SetProductID(v uuid.UUID) *OptimizationItemUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *OptimizationItemUpdate) SetNillableProductID(v *uuid.UUID) *OptimizationItemUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetStoreID sets the "store_id" field.
func (_u *OptimizationItemUpdate) SetStoreID(v uuid.UUID) *OptimizationItemUpdate {
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *OptimizationItemUpdate) SetNillableStoreID(v *uuid.UUID) *OptimizationItemUpdate {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// SetResultID sets the "result_id" field.
func (_u *OptimizationItemUpdate) SetResultID(v uuid.UUID) *OptimizationItemUpdate {
	_u.mutation.SetResultID(v)
	return _u
}

// SetNillableResultID sets the "result_id" field if the given value is not nil.
func (_u *OptimizationItemUpdate) SetNillableResultID(v *uuid.UUID) *OptimizationItemUpdate {
	if v != nil {
		_u.SetResultID(*v)
	}
	return _u
}

// SetResult sets the "result" edge to the OptimizationResult entity.
func (_u *OptimizationItemUpdate) SetResult(v *OptimizationResult) *OptimizationItemUpdate {
	return _u.SetResultID(v.ID)
}

// Mutation returns the OptimizationItemMutation object of the builder.
func (_u *OptimizationItemUpdate) Mutation() *OptimizationItemMutation {
	return _u.mutation
}

// ClearResult clears the "result" edge to the OptimizationResult entity.
func (_u *OptimizationItemUpdate) ClearResult() *OptimizationItemUpdate {
	_u.mutation.ClearResult()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OptimizationItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OptimizationItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OptimizationItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OptimizationItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OptimizationItemUpdate) check() error {
	if _u.mutation.ResultCleared() && len(_u.mutation.ResultIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OptimizationItem.result"`)
	}
	return nil
}

func (_u *OptimizationItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(optimizationitem.Table, optimizationitem.Columns, sqlgraph.NewFieldSpec(optimizationitem.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PriceKopecks(); ok {
		_spec.SetField(optimizationitem.FieldPriceKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPriceKopecks(); ok {
		_spec.AddField(optimizationitem.FieldPriceKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(optimizationitem.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StoreName(); ok {
		_spec.SetField(optimizationitem.FieldStoreName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(optimizationitem.FieldQuantity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(optimizationitem.FieldQuantity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(optimizationitem.FieldProductID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.StoreID(); ok {
		_spec.SetField(optimizationitem.FieldStoreID, field.TypeUUID, value)
	}
	if _u.mutation.ResultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   optimizationitem.ResultTable,
			Columns: []string{optimizationitem.ResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(optimizationresult.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   optimizationitem.ResultTable,
			Columns: []string{optimizationitem.ResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(optimizationresult.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{optimizationitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OptimizationItemUpdateOne is the builder for updating a single OptimizationItem entity.
type OptimizationItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OptimizationItemMutation
}

// SetPriceKopecks sets the "price_kopecks" field.
func (_u *OptimizationItemUpdateOne) SetPriceKopecks(v int64) *OptimizationItemUpdateOne {
	_u.mutation.ResetPriceKopecks()
	_u.mutation.SetPriceKopecks(v)
	return _u
}

// SetNillablePriceKopecks sets the "price_kopecks" field if the given value is not nil.
func (_u *OptimizationItemUpdateOne) SetNillablePriceKopecks(v *int64) *OptimizationItemUpdateOne {
	if v != nil {
		_u.SetPriceKopecks(*v)
	}
	return _u
}

// AddPriceKopecks adds value to the "price_kopecks" field.
func (_u *OptimizationItemUpdateOne) AddPriceKopecks(v int64) *OptimizationItemUpdateOne {
	_u.mutation.AddPriceKopecks(v)
	return _u
}

// SetProductName sets the "product_name" field.
func (_u *OptimizationItemUpdateOne) SetProductName(v string) *OptimizationItemUpdateOne {
	_u.mutation.SetProductName(v)
	return _u
}

// SetNillableProductName sets the "product_name" field if the given value is not nil.
func (_u *OptimizationItemUpdateOne) SetNillableProductName(v *string) *OptimizationItemUpdateOne {
	if v != nil {
		_u.SetProductName(*v)
	}
	return _u
}

// SetStoreName sets the "store_name" field.
func (_u *OptimizationItemUpdateOne) SetStoreName(v string) *OptimizationItemUpdateOne {
	_u.mutation.SetStoreName(v)
	return _u
}

// SetNillableStoreName sets the "store_name" field if the given value is not nil.
func (_u *OptimizationItemUpdateOne) SetNillableStoreName(v *string) *OptimizationItemUpdateOne {
	if v != nil {
		_u.SetStoreName(*v)
	}
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OptimizationItemUpdateOne) SetQuantity(v int16) *OptimizationItemUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OptimizationItemUpdateOne) SetNillableQuantity(v *int16) *OptimizationItemUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OptimizationItemUpdateOne) AddQuantity(v int16) *OptimizationItemUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *OptimizationItemUpdateOne) SetProductID(v uuid.UUID) *OptimizationItemUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *OptimizationItemUpdateOne) SetNillableProductID(v *uuid.UUID) *OptimizationItemUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// SetStoreID sets the "store_id" field.
func (_u *OptimizationItemUpdateOne) SetStoreID(v uuid.UUID) *OptimizationItemUpdateOne {
	_u.mutation.SetStoreID(v)
	return _u
}

// SetNillableStoreID sets the "store_id" field if the given value is not nil.
func (_u *OptimizationItemUpdateOne) SetNillableStoreID(v *uuid.UUID) *OptimizationItemUpdateOne {
	if v != nil {
		_u.SetStoreID(*v)
	}
	return _u
}

// SetResultID sets the "result_id" field.
func (_u *OptimizationItemUpdateOne) SetResultID(v uuid.UUID) *OptimizationItemUpdateOne {
	_u.mutation.SetResultID(v)
	return _u
}

// SetNillableResultID sets the "result_id" field if the given value is not nil.
func (_u *OptimizationItemUpdateOne) SetNillableResultID(v *uuid.UUID) *OptimizationItemUpdateOne {
	if v != nil {
		_u.SetResultID(*v)
	}
	return _u
}

// SetResult sets the "result" edge to the OptimizationResult entity.
func (_u *OptimizationItemUpdateOne) SetResult(v *OptimizationResult) *OptimizationItemUpdateOne {
	return _u.SetResultID(v.ID)
}

// Mutation returns the OptimizationItemMutation object of the builder.
func (_u *OptimizationItemUpdateOne) Mutation() *OptimizationItemMutation {
	return _u.mutation
}

// ClearResult clears the "result" edge to the OptimizationResult entity.
func (_u *OptimizationItemUpdateOne) ClearResult() *OptimizationItemUpdateOne {
	_u.mutation.ClearResult()
	return _u
}

// Where appends a list predicates to the OptimizationItemUpdate builder.
func (_u *OptimizationItemUpdateOne) Where(ps ...predicate.OptimizationItem) *OptimizationItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OptimizationItemUpdateOne) Select(field string, fields ...string) *OptimizationItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OptimizationItem entity.
func (_u *OptimizationItemUpdateOne) Save(ctx context.Context) (*OptimizationItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OptimizationItemUpdateOne) SaveX(ctx context.Context) *OptimizationItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OptimizationItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OptimizationItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OptimizationItemUpdateOne) check() error {
	if _u.mutation.ResultCleared() && len(_u.mutation.ResultIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OptimizationItem.result"`)
	}
	return nil
}

func (_u *OptimizationItemUpdateOne) sqlSave(ctx context.Context) (_node *OptimizationItem, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(optimizationitem.Table, optimizationitem.Columns, sqlgraph.NewFieldSpec(optimizationitem.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OptimizationItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, optimizationitem.FieldID)
		for _, f := range fields {
			if !optimizationitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != optimizationitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PriceKopecks(); ok {
		_spec.SetField(optimizationitem.FieldPriceKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPriceKopecks(); ok {
		_spec.AddField(optimizationitem.FieldPriceKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.ProductName(); ok {
		_spec.SetField(optimizationitem.FieldProductName, field.TypeString, value)
	}
	if value, ok := _u.mutation.StoreName(); ok {
		_spec.SetField(optimizationitem.FieldStoreName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(optimizationitem.FieldQuantity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(optimizationitem.FieldQuantity, field.TypeInt16, value)
	}
	if value, ok := _u.mutation.ProductID(); ok {
		_spec.SetField(optimizationitem.FieldProductID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.StoreID(); ok {
		_spec.SetField(optimizationitem.FieldStoreID, field.TypeUUID, value)
	}
	if _u.mutation.ResultCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   optimizationitem.ResultTable,
			Columns: []string{optimizationitem.ResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(optimizationresult.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ResultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   optimizationitem.ResultTable,
			Columns: []string{optimizationitem.ResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(optimizationresult.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OptimizationItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{optimizationitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
