// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/foodsea/optimization/ent/optimizationitem"
	"github.com/foodsea/optimization/ent/optimizationresult"
	"github.com/foodsea/optimization/ent/predicate"
	"github.com/foodsea/optimization/ent/substitution"
	"github.com/google/uuid"
)

// OptimizationResultUpdate is the builder for updating OptimizationResult entities.
type OptimizationResultUpdate struct {
	config
	hooks    []Hook
	mutation *OptimizationResultMutation
}

// Where appends a list predicates to the OptimizationResultUpdate builder.
func (_u *OptimizationResultUpdate) Where(ps ...predicate.OptimizationResult) *OptimizationResultUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OptimizationResultUpdate) SetUpdatedAt(v time.Time) *OptimizationResultUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTotalKopecks sets the "total_kopecks" field.
func (_u *OptimizationResultUpdate) SetTotalKopecks(v int64) *OptimizationResultUpdate {
	_u.mutation.ResetTotalKopecks()
	_u.mutation.SetTotalKopecks(v)
	return _u
}

// SetNillableTotalKopecks sets the "total_kopecks" field if the given value is not nil.
func (_u *OptimizationResultUpdate) SetNillableTotalKopecks(v *int64) *OptimizationResultUpdate {
	if v != nil {
		_u.SetTotalKopecks(*v)
	}
	return _u
}

// AddTotalKopecks adds value to the "total_kopecks" field.
func (_u *OptimizationResultUpdate) AddTotalKopecks(v int64) *OptimizationResultUpdate {
	_u.mutation.AddTotalKopecks(v)
	return _u
}

// SetDeliveryKopecks sets the "delivery_kopecks" field.
func (_u *OptimizationResultUpdate) SetDeliveryKopecks(v int64) *OptimizationResultUpdate {
	_u.mutation.ResetDeliveryKopecks()
	_u.mutation.SetDeliveryKopecks(v)
	return _u
}

// SetNillableDeliveryKopecks sets the "delivery_kopecks" field if the given value is not nil.
func (_u *OptimizationResultUpdate) SetNillableDeliveryKopecks(v *int64) *OptimizationResultUpdate {
	if v != nil {
		_u.SetDeliveryKopecks(*v)
	}
	return _u
}

// AddDeliveryKopecks adds value to the "delivery_kopecks" field.
func (_u *OptimizationResultUpdate) AddDeliveryKopecks(v int64) *OptimizationResultUpdate {
	_u.mutation.AddDeliveryKopecks(v)
	return _u
}

// SetSavingsKopecks sets the "savings_kopecks" field.
func (_u *OptimizationResultUpdate) SetSavingsKopecks(v int64) *OptimizationResultUpdate {
	_u.mutation.ResetSavingsKopecks()
	_u.mutation.SetSavingsKopecks(v)
	return _u
}

// SetNillableSavingsKopecks sets the "savings_kopecks" field if the given value is not nil.
func (_u *OptimizationResultUpdate) SetNillableSavingsKopecks(v *int64) *OptimizationResultUpdate {
	if v != nil {
		_u.SetSavingsKopecks(*v)
	}
	return _u
}

// AddSavingsKopecks adds value to the "savings_kopecks" field.
func (_u *OptimizationResultUpdate) AddSavingsKopecks(v int64) *OptimizationResultUpdate {
	_u.mutation.AddSavingsKopecks(v)
	return _u
}

// SetCartHash sets the "cart_hash" field.
func (_u *OptimizationResultUpdate) SetCartHash(v string) *OptimizationResultUpdate {
	_u.mutation.SetCartHash(v)
	return _u
}

// SetNillableCartHash sets the "cart_hash" field if the given value is not nil.
func (_u *OptimizationResultUpdate) SetNillableCartHash(v *string) *OptimizationResultUpdate {
	if v != nil {
		_u.SetCartHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OptimizationResultUpdate) SetStatus(v string) *OptimizationResultUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OptimizationResultUpdate) SetNillableStatus(v *string) *OptimizationResultUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OptimizationResultUpdate) SetUserID(v uuid.UUID) *OptimizationResultUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OptimizationResultUpdate) SetNillableUserID(v *uuid.UUID) *OptimizationResultUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetIsApproximate sets the "is_approximate" field.
func (_u *OptimizationResultUpdate) SetIsApproximate(v bool) *OptimizationResultUpdate {
	_u.mutation.SetIsApproximate(v)
	return _u
}

// SetNillableIsApproximate sets the "is_approximate" field if the given value is not nil.
func (_u *OptimizationResultUpdate) SetNillableIsApproximate(v *bool) *OptimizationResultUpdate {
	if v != nil {
		_u.SetIsApproximate(*v)
	}
	return _u
}

// AddItemIDs adds the "items" edge to the OptimizationItem entity by IDs.
func (_u *OptimizationResultUpdate) AddItemIDs(ids ...uuid.UUID) *OptimizationResultUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the OptimizationItem entity.
func (_u *OptimizationResultUpdate) AddItems(v ...*OptimizationItem) *OptimizationResultUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// AddSubstitutionIDs adds the "substitutions" edge to the Substitution entity by IDs.
func (_u *OptimizationResultUpdate) AddSubstitutionIDs(ids ...uuid.UUID) *OptimizationResultUpdate {
	_u.mutation.AddSubstitutionIDs(ids...)
	return _u
}

// AddSubstitutions adds the "substitutions" edges to the Substitution entity.
func (_u *OptimizationResultUpdate) AddSubstitutions(v ...*Substitution) *OptimizationResultUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubstitutionIDs(ids...)
}

// Mutation returns the OptimizationResultMutation object of the builder.
func (_u *OptimizationResultUpdate) Mutation() *OptimizationResultMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the OptimizationItem entity.
func (_u *OptimizationResultUpdate) ClearItems() *OptimizationResultUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to OptimizationItem entities by IDs.
func (_u *OptimizationResultUpdate) RemoveItemIDs(ids ...uuid.UUID) *OptimizationResultUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to OptimizationItem entities.
func (_u *OptimizationResultUpdate) RemoveItems(v ...*OptimizationItem) *OptimizationResultUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// ClearSubstitutions clears all "substitutions" edges to the Substitution entity.
func (_u *OptimizationResultUpdate) ClearSubstitutions() *OptimizationResultUpdate {
	_u.mutation.ClearSubstitutions()
	return _u
}

// RemoveSubstitutionIDs removes the "substitutions" edge to Substitution entities by IDs.
func (_u *OptimizationResultUpdate) RemoveSubstitutionIDs(ids ...uuid.UUID) *OptimizationResultUpdate {
	_u.mutation.RemoveSubstitutionIDs(ids...)
	return _u
}

// RemoveSubstitutions removes "substitutions" edges to Substitution entities.
func (_u *OptimizationResultUpdate) RemoveSubstitutions(v ...*Substitution) *OptimizationResultUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubstitutionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OptimizationResultUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OptimizationResultUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OptimizationResultUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OptimizationResultUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OptimizationResultUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if optimizationresult.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized optimizationresult.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := optimizationresult.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (_u *OptimizationResultUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(optimizationresult.Table, optimizationresult.Columns, sqlgraph.NewFieldSpec(optimizationresult.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(optimizationresult.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TotalKopecks(); ok {
		_spec.SetField(optimizationresult.FieldTotalKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalKopecks(); ok {
		_spec.AddField(optimizationresult.FieldTotalKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeliveryKopecks(); ok {
		_spec.SetField(optimizationresult.FieldDeliveryKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeliveryKopecks(); ok {
		_spec.AddField(optimizationresult.FieldDeliveryKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SavingsKopecks(); ok {
		_spec.SetField(optimizationresult.FieldSavingsKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSavingsKopecks(); ok {
		_spec.AddField(optimizationresult.FieldSavingsKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CartHash(); ok {
		_spec.SetField(optimizationresult.FieldCartHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(optimizationresult.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(optimizationresult.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.IsApproximate(); ok {
		_spec.SetField(optimizationresult.FieldIsApproximate, field.TypeBool, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   optimizationresult.ItemsTable,
			Columns: []string{optimizationresult.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(optimizationitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   optimizationresult.ItemsTable,
			Columns: []string{optimizationresult.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(optimizationitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   optimizationresult.ItemsTable,
			Columns: []string{optimizationresult.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(optimizationitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubstitutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   optimizationresult.SubstitutionsTable,
			Columns: []string{optimizationresult.SubstitutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(substitution.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubstitutionsIDs(); len(nodes) > 0 && !_u.mutation.SubstitutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   optimizationresult.SubstitutionsTable,
			Columns: []string{optimizationresult.SubstitutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(substitution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubstitutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   optimizationresult.SubstitutionsTable,
			Columns: []string{optimizationresult.SubstitutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(substitution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{optimizationresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OptimizationResultUpdateOne is the builder for updating a single OptimizationResult entity.
type OptimizationResultUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OptimizationResultMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OptimizationResultUpdateOne) SetUpdatedAt(v time.Time) *OptimizationResultUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTotalKopecks sets the "total_kopecks" field.
func (_u *OptimizationResultUpdateOne) SetTotalKopecks(v int64) *OptimizationResultUpdateOne {
	_u.mutation.ResetTotalKopecks()
	_u.mutation.SetTotalKopecks(v)
	return _u
}

// SetNillableTotalKopecks sets the "total_kopecks" field if the given value is not nil.
func (_u *OptimizationResultUpdateOne) SetNillableTotalKopecks(v *int64) *OptimizationResultUpdateOne {
	if v != nil {
		_u.SetTotalKopecks(*v)
	}
	return _u
}

// AddTotalKopecks adds value to the "total_kopecks" field.
func (_u *OptimizationResultUpdateOne) AddTotalKopecks(v int64) *OptimizationResultUpdateOne {
	_u.mutation.AddTotalKopecks(v)
	return _u
}

// SetDeliveryKopecks sets the "delivery_kopecks" field.
func (_u *OptimizationResultUpdateOne) SetDeliveryKopecks(v int64) *OptimizationResultUpdateOne {
	_u.mutation.ResetDeliveryKopecks()
	_u.mutation.SetDeliveryKopecks(v)
	return _u
}

// SetNillableDeliveryKopecks sets the "delivery_kopecks" field if the given value is not nil.
func (_u *OptimizationResultUpdateOne) SetNillableDeliveryKopecks(v *int64) *OptimizationResultUpdateOne {
	if v != nil {
		_u.SetDeliveryKopecks(*v)
	}
	return _u
}

// AddDeliveryKopecks adds value to the "delivery_kopecks" field.
func (_u *OptimizationResultUpdateOne) AddDeliveryKopecks(v int64) *OptimizationResultUpdateOne {
	_u.mutation.AddDeliveryKopecks(v)
	return _u
}

// SetSavingsKopecks sets the "savings_kopecks" field.
func (_u *OptimizationResultUpdateOne) SetSavingsKopecks(v int64) *OptimizationResultUpdateOne {
	_u.mutation.ResetSavingsKopecks()
	_u.mutation.SetSavingsKopecks(v)
	return _u
}

// SetNillableSavingsKopecks sets the "savings_kopecks" field if the given value is not nil.
func (_u *OptimizationResultUpdateOne) SetNillableSavingsKopecks(v *int64) *OptimizationResultUpdateOne {
	if v != nil {
		_u.SetSavingsKopecks(*v)
	}
	return _u
}

// AddSavingsKopecks adds value to the "savings_kopecks" field.
func (_u *OptimizationResultUpdateOne) AddSavingsKopecks(v int64) *OptimizationResultUpdateOne {
	_u.mutation.AddSavingsKopecks(v)
	return _u
}

// SetCartHash sets the "cart_hash" field.
func (_u *OptimizationResultUpdateOne) SetCartHash(v string) *OptimizationResultUpdateOne {
	_u.mutation.SetCartHash(v)
	return _u
}

// SetNillableCartHash sets the "cart_hash" field if the given value is not nil.
func (_u *OptimizationResultUpdateOne) SetNillableCartHash(v *string) *OptimizationResultUpdateOne {
	if v != nil {
		_u.SetCartHash(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OptimizationResultUpdateOne) SetStatus(v string) *OptimizationResultUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OptimizationResultUpdateOne) SetNillableStatus(v *string) *OptimizationResultUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *OptimizationResultUpdateOne) SetUserID(v uuid.UUID) *OptimizationResultUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *OptimizationResultUpdateOne) SetNillableUserID(v *uuid.UUID) *OptimizationResultUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetIsApproximate sets the "is_approximate" field.
func (_u *OptimizationResultUpdateOne) SetIsApproximate(v bool) *OptimizationResultUpdateOne {
	_u.mutation.SetIsApproximate(v)
	return _u
}

// SetNillableIsApproximate sets the "is_approximate" field if the given value is not nil.
func (_u *OptimizationResultUpdateOne) SetNillableIsApproximate(v *bool) *OptimizationResultUpdateOne {
	if v != nil {
		_u.SetIsApproximate(*v)
	}
	return _u
}

// AddItemIDs adds the "items" edge to the OptimizationItem entity by IDs.
func (_u *OptimizationResultUpdateOne) AddItemIDs(ids ...uuid.UUID) *OptimizationResultUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the OptimizationItem entity.
func (_u *OptimizationResultUpdateOne) AddItems(v ...*OptimizationItem) *OptimizationResultUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// AddSubstitutionIDs adds the "substitutions" edge to the Substitution entity by IDs.
func (_u *OptimizationResultUpdateOne) AddSubstitutionIDs(ids ...uuid.UUID) *OptimizationResultUpdateOne {
	_u.mutation.AddSubstitutionIDs(ids...)
	return _u
}

// AddSubstitutions adds the "substitutions" edges to the Substitution entity.
func (_u *OptimizationResultUpdateOne) AddSubstitutions(v ...*Substitution) *OptimizationResultUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubstitutionIDs(ids...)
}

// Mutation returns the OptimizationResultMutation object of the builder.
func (_u *OptimizationResultUpdateOne) Mutation() *OptimizationResultMutation {
	return _u.mutation
}

// ClearItems clears all "items" edges to the OptimizationItem entity.
func (_u *OptimizationResultUpdateOne) ClearItems() *OptimizationResultUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to OptimizationItem entities by IDs.
func (_u *OptimizationResultUpdateOne) RemoveItemIDs(ids ...uuid.UUID) *OptimizationResultUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to OptimizationItem entities.
func (_u *OptimizationResultUpdateOne) RemoveItems(v ...*OptimizationItem) *OptimizationResultUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// ClearSubstitutions clears all "substitutions" edges to the Substitution entity.
func (_u *OptimizationResultUpdateOne) ClearSubstitutions() *OptimizationResultUpdateOne {
	_u.mutation.ClearSubstitutions()
	return _u
}

// RemoveSubstitutionIDs removes the "substitutions" edge to Substitution entities by IDs.
func (_u *OptimizationResultUpdateOne) RemoveSubstitutionIDs(ids ...uuid.UUID) *OptimizationResultUpdateOne {
	_u.mutation.RemoveSubstitutionIDs(ids...)
	return _u
}

// RemoveSubstitutions removes "substitutions" edges to Substitution entities.
func (_u *OptimizationResultUpdateOne) RemoveSubstitutions(v ...*Substitution) *OptimizationResultUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubstitutionIDs(ids...)
}

// Where appends a list predicates to the OptimizationResultUpdate builder.
func (_u *OptimizationResultUpdateOne) Where(ps ...predicate.OptimizationResult) *OptimizationResultUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OptimizationResultUpdateOne) Select(field string, fields ...string) *OptimizationResultUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OptimizationResult entity.
func (_u *OptimizationResultUpdateOne) Save(ctx context.Context) (*OptimizationResult, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OptimizationResultUpdateOne) SaveX(ctx context.Context) *OptimizationResult {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OptimizationResultUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OptimizationResultUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OptimizationResultUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if optimizationresult.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized optimizationresult.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := optimizationresult.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

func (_u *OptimizationResultUpdateOne) sqlSave(ctx context.Context) (_node *OptimizationResult, err error) {
	_spec := sqlgraph.NewUpdateSpec(optimizationresult.Table, optimizationresult.Columns, sqlgraph.NewFieldSpec(optimizationresult.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OptimizationResult.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, optimizationresult.FieldID)
		for _, f := range fields {
			if !optimizationresult.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != optimizationresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(optimizationresult.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TotalKopecks(); ok {
		_spec.SetField(optimizationresult.FieldTotalKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTotalKopecks(); ok {
		_spec.AddField(optimizationresult.FieldTotalKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.DeliveryKopecks(); ok {
		_spec.SetField(optimizationresult.FieldDeliveryKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeliveryKopecks(); ok {
		_spec.AddField(optimizationresult.FieldDeliveryKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.SavingsKopecks(); ok {
		_spec.SetField(optimizationresult.FieldSavingsKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSavingsKopecks(); ok {
		_spec.AddField(optimizationresult.FieldSavingsKopecks, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CartHash(); ok {
		_spec.SetField(optimizationresult.FieldCartHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(optimizationresult.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(optimizationresult.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.IsApproximate(); ok {
		_spec.SetField(optimizationresult.FieldIsApproximate, field.TypeBool, value)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   optimizationresult.ItemsTable,
			Columns: []string{optimizationresult.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(optimizationitem.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   optimizationresult.ItemsTable,
			Columns: []string{optimizationresult.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(optimizationitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   optimizationresult.ItemsTable,
			Columns: []string{optimizationresult.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(optimizationitem.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubstitutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   optimizationresult.SubstitutionsTable,
			Columns: []string{optimizationresult.SubstitutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(substitution.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubstitutionsIDs(); len(nodes) > 0 && !_u.mutation.SubstitutionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   optimizationresult.SubstitutionsTable,
			Columns: []string{optimizationresult.SubstitutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(substitution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubstitutionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   optimizationresult.SubstitutionsTable,
			Columns: []string{optimizationresult.SubstitutionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(substitution.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OptimizationResult{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{optimizationresult.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
