// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/foodsea/optimization/ent/optimizationresult"
	"github.com/google/uuid"
)

// OptimizationResult is the model entity for the OptimizationResult schema.
type OptimizationResult struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// TotalKopecks holds the value of the "total_kopecks" field.
	TotalKopecks int64 `json:"total_kopecks,omitempty"`
	// DeliveryKopecks holds the value of the "delivery_kopecks" field.
	DeliveryKopecks int64 `json:"delivery_kopecks,omitempty"`
	// SavingsKopecks holds the value of the "savings_kopecks" field.
	SavingsKopecks int64 `json:"savings_kopecks,omitempty"`
	// CartHash holds the value of the "cart_hash" field.
	CartHash string `json:"cart_hash,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// IsApproximate holds the value of the "is_approximate" field.
	IsApproximate bool `json:"is_approximate,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OptimizationResultQuery when eager-loading is set.
	Edges        OptimizationResultEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OptimizationResultEdges holds the relations/edges for other nodes in the graph.
type OptimizationResultEdges struct {
	// Items holds the value of the items edge.
	Items []*OptimizationItem `json:"items,omitempty"`
	// Substitutions holds the value of the substitutions edge.
	Substitutions []*Substitution `json:"substitutions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e OptimizationResultEdges) ItemsOrErr() ([]*OptimizationItem, error) {
	if e.loadedTypes[0] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// SubstitutionsOrErr returns the Substitutions value or an error if the edge
// was not loaded in eager-loading.
func (e OptimizationResultEdges) SubstitutionsOrErr() ([]*Substitution, error) {
	if e.loadedTypes[1] {
		return e.Substitutions, nil
	}
	return nil, &NotLoadedError{edge: "substitutions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OptimizationResult) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case optimizationresult.FieldIsApproximate:
			values[i] = new(sql.NullBool)
		case optimizationresult.FieldTotalKopecks, optimizationresult.FieldDeliveryKopecks, optimizationresult.FieldSavingsKopecks:
			values[i] = new(sql.NullInt64)
		case optimizationresult.FieldCartHash, optimizationresult.FieldStatus:
			values[i] = new(sql.NullString)
		case optimizationresult.FieldCreatedAt, optimizationresult.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case optimizationresult.FieldID, optimizationresult.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OptimizationResult fields.
func (_m *OptimizationResult) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case optimizationresult.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case optimizationresult.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case optimizationresult.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case optimizationresult.FieldTotalKopecks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_kopecks", values[i])
			} else if value.Valid {
				_m.TotalKopecks = value.Int64
			}
		case optimizationresult.FieldDeliveryKopecks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delivery_kopecks", values[i])
			} else if value.Valid {
				_m.DeliveryKopecks = value.Int64
			}
		case optimizationresult.FieldSavingsKopecks:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field savings_kopecks", values[i])
			} else if value.Valid {
				_m.SavingsKopecks = value.Int64
			}
		case optimizationresult.FieldCartHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cart_hash", values[i])
			} else if value.Valid {
				_m.CartHash = value.String
			}
		case optimizationresult.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case optimizationresult.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case optimizationresult.FieldIsApproximate:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_approximate", values[i])
			} else if value.Valid {
				_m.IsApproximate = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OptimizationResult.
// This includes values selected through modifiers, order, etc.
func (_m *OptimizationResult) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryItems queries the "items" edge of the OptimizationResult entity.
func (_m *OptimizationResult) QueryItems() *OptimizationItemQuery {
	return NewOptimizationResultClient(_m.config).QueryItems(_m)
}

// QuerySubstitutions queries the "substitutions" edge of the OptimizationResult entity.
func (_m *OptimizationResult) QuerySubstitutions() *SubstitutionQuery {
	return NewOptimizationResultClient(_m.config).QuerySubstitutions(_m)
}

// Update returns a builder for updating this OptimizationResult.
// Note that you need to call OptimizationResult.Unwrap() before calling this method if this OptimizationResult
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OptimizationResult) Update() *OptimizationResultUpdateOne {
	return NewOptimizationResultClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OptimizationResult entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OptimizationResult) Unwrap() *OptimizationResult {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OptimizationResult is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OptimizationResult) String() string {
	var builder strings.Builder
	builder.WriteString("OptimizationResult(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("total_kopecks=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalKopecks))
	builder.WriteString(", ")
	builder.WriteString("delivery_kopecks=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeliveryKopecks))
	builder.WriteString(", ")
	builder.WriteString("savings_kopecks=")
	builder.WriteString(fmt.Sprintf("%v", _m.SavingsKopecks))
	builder.WriteString(", ")
	builder.WriteString("cart_hash=")
	builder.WriteString(_m.CartHash)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("is_approximate=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsApproximate))
	builder.WriteByte(')')
	return builder.String()
}

// OptimizationResults is a parsable slice of OptimizationResult.
type OptimizationResults []*OptimizationResult
