// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/foodsea/optimization/ent/optimizationresult"
	"github.com/foodsea/optimization/ent/substitution"
	"github.com/google/uuid"
)

// SubstitutionCreate is the builder for creating a Substitution entity.
type SubstitutionCreate struct {
	config
	mutation *SubstitutionMutation
	hooks    []Hook
}

// SetTotalSavingKopecks sets the "total_saving_kopecks" field.
func (_c *SubstitutionCreate) SetTotalSavingKopecks(v int64) *SubstitutionCreate {
	_c.mutation.SetTotalSavingKopecks(v)
	return _c
}

// SetPriceDeltaKopecks sets the "price_delta_kopecks" field.
func (_c *SubstitutionCreate) SetPriceDeltaKopecks(v int64) *SubstitutionCreate {
	_c.mutation.SetPriceDeltaKopecks(v)
	return _c
}

// SetDeliveryDeltaKopecks sets the "delivery_delta_kopecks" field.
func (_c *SubstitutionCreate) SetDeliveryDeltaKopecks(v int64) *SubstitutionCreate {
	_c.mutation.SetDeliveryDeltaKopecks(v)
	return _c
}

// SetOldPriceKopecks sets the "old_price_kopecks" field.
func (_c *SubstitutionCreate) SetOldPriceKopecks(v int64) *SubstitutionCreate {
	_c.mutation.SetOldPriceKopecks(v)
	return _c
}

// SetNewPriceKopecks sets the "new_price_kopecks" field.
func (_c *SubstitutionCreate) SetNewPriceKopecks(v int64) *SubstitutionCreate {
	_c.mutation.SetNewPriceKopecks(v)
	return _c
}

// SetAnalogProductName sets the "analog_product_name" field.
func (_c *SubstitutionCreate) SetAnalogProductName(v string) *SubstitutionCreate {
	_c.mutation.SetAnalogProductName(v)
	return _c
}

// SetNewStoreName sets the "new_store_name" field.
func (_c *SubstitutionCreate) SetNewStoreName(v string) *SubstitutionCreate {
	_c.mutation.SetNewStoreName(v)
	return _c
}

// SetOriginalProductName sets the "original_product_name" field.
func (_c *SubstitutionCreate) SetOriginalProductName(v string) *SubstitutionCreate {
	_c.mutation.SetOriginalProductName(v)
	return _c
}

// SetScore sets the "score" field.
func (_c *SubstitutionCreate) SetScore(v float64) *SubstitutionCreate {
	_c.mutation.SetScore(v)
	return _c
}

// SetOriginalStoreID sets the "original_store_id" field.
func (_c *SubstitutionCreate) SetOriginalStoreID(v uuid.UUID) *SubstitutionCreate {
	_c.mutation.SetOriginalStoreID(v)
	return _c
}

// SetOriginalProductID sets the "original_product_id" field.
func (_c *SubstitutionCreate) SetOriginalProductID(v uuid.UUID) *SubstitutionCreate {
	_c.mutation.SetOriginalProductID(v)
	return _c
}

// SetAnalogProductID sets the "analog_product_id" field.
func (_c *SubstitutionCreate) SetAnalogProductID(v uuid.UUID) *SubstitutionCreate {
	_c.mutation.SetAnalogProductID(v)
	return _c
}

// SetNewStoreID sets the "new_store_id" field.
func (_c *SubstitutionCreate) SetNewStoreID(v uuid.UUID) *SubstitutionCreate {
	_c.mutation.SetNewStoreID(v)
	return _c
}

// SetIsCrossStore sets the "is_cross_store" field.
func (_c *SubstitutionCreate) SetIsCrossStore(v bool) *SubstitutionCreate {
	_c.mutation.SetIsCrossStore(v)
	return _c
}

// SetResultID sets the "result_id" field.
func (_c *SubstitutionCreate) SetResultID(v uuid.UUID) *SubstitutionCreate {
	_c.mutation.SetResultID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *SubstitutionCreate) SetID(v uuid.UUID) *SubstitutionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SubstitutionCreate) SetNillableID(v *uuid.UUID) *SubstitutionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetResult sets the "result" edge to the OptimizationResult entity.
func (_c *SubstitutionCreate) SetResult(v *OptimizationResult) *SubstitutionCreate {
	return _c.SetResultID(v.ID)
}

// Mutation returns the SubstitutionMutation object of the builder.
func (_c *SubstitutionCreate) Mutation() *SubstitutionMutation {
	return _c.mutation
}

// Save creates the Substitution in the database.
func (_c *SubstitutionCreate) Save(ctx context.Context) (*Substitution, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SubstitutionCreate) SaveX(ctx context.Context) *Substitution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubstitutionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubstitutionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SubstitutionCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := substitution.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SubstitutionCreate) check() error {
	if _, ok := _c.mutation.TotalSavingKopecks(); !ok {
		return &ValidationError{Name: "total_saving_kopecks", err: errors.New(`ent: missing required field "Substitution.total_saving_kopecks"`)}
	}
	if _, ok := _c.mutation.PriceDeltaKopecks(); !ok {
		return &ValidationError{Name: "price_delta_kopecks", err: errors.New(`ent: missing required field "Substitution.price_delta_kopecks"`)}
	}
	if _, ok := _c.mutation.DeliveryDeltaKopecks(); !ok {
		return &ValidationError{Name: "delivery_delta_kopecks", err: errors.New(`ent: missing required field "Substitution.delivery_delta_kopecks"`)}
	}
	if _, ok := _c.mutation.OldPriceKopecks(); !ok {
		return &ValidationError{Name: "old_price_kopecks", err: errors.New(`ent: missing required field "Substitution.old_price_kopecks"`)}
	}
	if _, ok := _c.mutation.NewPriceKopecks(); !ok {
		return &ValidationError{Name: "new_price_kopecks", err: errors.New(`ent: missing required field "Substitution.new_price_kopecks"`)}
	}
	if _, ok := _c.mutation.AnalogProductName(); !ok {
		return &ValidationError{Name: "analog_product_name", err: errors.New(`ent: missing required field "Substitution.analog_product_name"`)}
	}
	if _, ok := _c.mutation.NewStoreName(); !ok {
		return &ValidationError{Name: "new_store_name", err: errors.New(`ent: missing required field "Substitution.new_store_name"`)}
	}
	if _, ok := _c.mutation.OriginalProductName(); !ok {
		return &ValidationError{Name: "original_product_name", err: errors.New(`ent: missing required field "Substitution.original_product_name"`)}
	}
	if _, ok := _c.mutation.Score(); !ok {
		return &ValidationError{Name: "score", err: errors.New(`ent: missing required field "Substitution.score"`)}
	}
	if _, ok := _c.mutation.OriginalStoreID(); !ok {
		return &ValidationError{Name: "original_store_id", err: errors.New(`ent: missing required field "Substitution.original_store_id"`)}
	}
	if _, ok := _c.mutation.OriginalProductID(); !ok {
		return &ValidationError{Name: "original_product_id", err: errors.New(`ent: missing required field "Substitution.original_product_id"`)}
	}
	if _, ok := _c.mutation.AnalogProductID(); !ok {
		return &ValidationError{Name: "analog_product_id", err: errors.New(`ent: missing required field "Substitution.analog_product_id"`)}
	}
	if _, ok := _c.mutation.NewStoreID(); !ok {
		return &ValidationError{Name: "new_store_id", err: errors.New(`ent: missing required field "Substitution.new_store_id"`)}
	}
	if _, ok := _c.mutation.IsCrossStore(); !ok {
		return &ValidationError{Name: "is_cross_store", err: errors.New(`ent: missing required field "Substitution.is_cross_store"`)}
	}
	if _, ok := _c.mutation.ResultID(); !ok {
		return &ValidationError{Name: "result_id", err: errors.New(`ent: missing required field "Substitution.result_id"`)}
	}
	if len(_c.mutation.ResultIDs()) == 0 {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required edge "Substitution.result"`)}
	}
	return nil
}

func (_c *SubstitutionCreate) sqlSave(ctx context.Context) (*Substitution, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SubstitutionCreate) createSpec() (*Substitution, *sqlgraph.CreateSpec) {
	var (
		_node = &Substitution{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(substitution.Table, sqlgraph.NewFieldSpec(substitution.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TotalSavingKopecks(); ok {
		_spec.SetField(substitution.FieldTotalSavingKopecks, field.TypeInt64, value)
		_node.TotalSavingKopecks = value
	}
	if value, ok := _c.mutation.PriceDeltaKopecks(); ok {
		_spec.SetField(substitution.FieldPriceDeltaKopecks, field.TypeInt64, value)
		_node.PriceDeltaKopecks = value
	}
	if value, ok := _c.mutation.DeliveryDeltaKopecks(); ok {
		_spec.SetField(substitution.FieldDeliveryDeltaKopecks, field.TypeInt64, value)
		_node.DeliveryDeltaKopecks = value
	}
	if value, ok := _c.mutation.OldPriceKopecks(); ok {
		_spec.SetField(substitution.FieldOldPriceKopecks, field.TypeInt64, value)
		_node.OldPriceKopecks = value
	}
	if value, ok := _c.mutation.NewPriceKopecks(); ok {
		_spec.SetField(substitution.FieldNewPriceKopecks, field.TypeInt64, value)
		_node.NewPriceKopecks = value
	}
	if value, ok := _c.mutation.AnalogProductName(); ok {
		_spec.SetField(substitution.FieldAnalogProductName, field.TypeString, value)
		_node.AnalogProductName = value
	}
	if value, ok := _c.mutation.NewStoreName(); ok {
		_spec.SetField(substitution.FieldNewStoreName, field.TypeString, value)
		_node.NewStoreName = value
	}
	if value, ok := _c.mutation.OriginalProductName(); ok {
		_spec.SetField(substitution.FieldOriginalProductName, field.TypeString, value)
		_node.OriginalProductName = value
	}
	if value, ok := _c.mutation.Score(); ok {
		_spec.SetField(substitution.FieldScore, field.TypeFloat64, value)
		_node.Score = value
	}
	if value, ok := _c.mutation.OriginalStoreID(); ok {
		_spec.SetField(substitution.FieldOriginalStoreID, field.TypeUUID, value)
		_node.OriginalStoreID = value
	}
	if value, ok := _c.mutation.OriginalProductID(); ok {
		_spec.SetField(substitution.FieldOriginalProductID, field.TypeUUID, value)
		_node.OriginalProductID = value
	}
	if value, ok := _c.mutation.AnalogProductID(); ok {
		_spec.SetField(substitution.FieldAnalogProductID, field.TypeUUID, value)
		_node.AnalogProductID = value
	}
	if value, ok := _c.mutation.NewStoreID(); ok {
		_spec.SetField(substitution.FieldNewStoreID, field.TypeUUID, value)
		_node.NewStoreID = value
	}
	if value, ok := _c.mutation.IsCrossStore(); ok {
		_spec.SetField(substitution.FieldIsCrossStore, field.TypeBool, value)
		_node.IsCrossStore = value
	}
	if nodes := _c.mutation.ResultIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   substitution.ResultTable,
			Columns: []string{substitution.ResultColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(optimizationresult.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ResultID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SubstitutionCreateBulk is the builder for creating many Substitution entities in bulk.
type SubstitutionCreateBulk struct {
	config
	err      error
	builders []*SubstitutionCreate
}

// Save creates the Substitution entities in the database.
func (_c *SubstitutionCreateBulk) Save(ctx context.Context) ([]*Substitution, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Substitution, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SubstitutionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SubstitutionCreateBulk) SaveX(ctx context.Context) []*Substitution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SubstitutionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SubstitutionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
